/* ÔN VĂN THEO NGÀY · 22/09 → 03/10/2026 — chuẩn bị cho bài kiểm tra Ngữ văn
   (Đọc hiểu + Tiếng Việt 5 điểm · Viết đoạn văn 5 điểm).
   Cùng khuôn với giang-bai.js: mỗi bài có trường ngay → tự hiện ở trang chủ mục "Hôm nay mẹ giảng" đúng ngày
   và trong trang tuần mục "Mẹ giảng thêm". Mỗi bài 20–30 phút: đọc phần giảng, nhớ mẹo, làm phần tự kiểm tra. */
window.KIM_GIANG = window.KIM_GIANG || {};

/* ===== Thứ Ba 22/09 · Ngôi kể ===== */
window.KIM_GIANG["on-van-0922"] = {
  mon: "van",
  ngay: "2026-09-22",
  tieuDe: "Ôn Văn ngày 1 · Ngôi kể và tác dụng của ngôi kể",
  sgk: "Ngữ văn 7 tập 1, Tri thức ngữ văn Bài 1 (tr. 10) · Bầy chim chìa vôi, Đi lấy mật",
  motCau: "Truyện nào cũng có một người đứng ra kể. Người đó có thể xưng “tôi” và kể chuyện của chính mình (ngôi thứ nhất), hoặc giấu mặt, gọi nhân vật bằng tên và kể như một người đứng ngoài nhìn vào (ngôi thứ ba). Đề gần như chắc chắn hỏi: truyện kể theo ngôi nào, dựa vào đâu mà biết, và kể như thế có tác dụng gì. Ba câu này Kim trả lời theo mẫu là lấy trọn điểm.",
  phan: [
    {
      ten: "Nhận ra ngôi kể trong 10 giây",
      doan: ["Chỉ cần nhìn vào cách gọi nhân vật chính."],
      kn: [
        { ten: "Ngôi thứ nhất", de: "Người kể xưng “tôi”, “em”, “mình”, “chúng tôi” và là một nhân vật trong truyện.",
          vd: "“Đi lấy mật”: An xưng “tôi”, kể chuyện chính mình theo tía nuôi vào rừng U Minh lấy mật ong. → Ngôi thứ nhất." },
        { ten: "Ngôi thứ ba", de: "Người kể không xuất hiện, gọi nhân vật bằng tên hoặc “nó”, “anh”, “cô bé”…",
          vd: "“Bầy chim chìa vôi”: người kể gọi hai nhân vật là “Mên”, “Mon”, không ai xưng tôi. → Ngôi thứ ba." },
      ],
      hop: { nhan: "Bẫy hay gặp", chu: "Trong lời thoại, nhân vật vẫn xưng “tôi”, “tao”, “em” với nhau. Ví dụ Mon nói với Mên: “Anh ơi, em sợ…”. Đó là lời nhân vật nói, KHÔNG phải lời người kể. Muốn biết ngôi kể, Kim nhìn vào phần kể chuyện nằm ngoài dấu ngoặc kép hoặc ngoài gạch đầu dòng." },
    },
    {
      ten: "Tác dụng của mỗi ngôi kể (học thuộc hai câu này)",
      doan: ["Đề hỏi “nêu tác dụng của ngôi kể” thì Kim viết đúng câu dưới đây, rồi thêm một vế nối với truyện đang hỏi."],
      buoc: [
        { so: 1, ten: "Ngôi thứ nhất", de: "Người kể trực tiếp tham gia câu chuyện nên kể lại được những gì mình tận mắt thấy, đồng thời bộc lộ suy nghĩ, cảm xúc của bản thân. Câu chuyện vì thế chân thực, gần gũi, người đọc như được sống cùng nhân vật.",
          vd: "Với “Đi lấy mật”: An kể theo ngôi thứ nhất nên cảnh rừng U Minh hiện lên qua đôi mắt tò mò của một cậu bé, và người đọc cảm nhận được sự thích thú, ngạc nhiên của An khi lần đầu đi “ăn ong”." },
        { so: 2, ten: "Ngôi thứ ba", de: "Người kể đứng ngoài câu chuyện nên có thể kể mọi việc xảy ra với nhiều nhân vật, ở nhiều nơi, và cả suy nghĩ bên trong của họ. Cách kể này khách quan, linh hoạt, bao quát.",
          vd: "Với “Bầy chim chìa vôi”: người kể vừa kể được cuộc trò chuyện của hai anh em trong nhà, vừa tả được bãi cát giữa sông và bầy chim non, lại cho ta biết cả nỗi lo trong lòng Mon lẫn sự bối rối của Mên." },
      ],
      hop: { nhan: "Mẫu câu trả lời trọn điểm", chu: "Truyện được kể theo ngôi thứ … Dấu hiệu: người kể xưng “tôi” / gọi nhân vật bằng tên. Tác dụng: (chép câu tác dụng ở trên) … Nhờ vậy, trong truyện này, … (một vế nối với nội dung truyện). Ba ý, khoảng ba câu là đủ." },
    },
    {
      ten: "Nếu đề cho đoạn trích lạ, không phải bài đã học",
      doan: ["Đề kiểm tra thường lấy một đoạn truyện ngoài sách. Kim vẫn làm đúng ba bước: tìm chữ “tôi” trong phần lời kể, kết luận ngôi, chép câu tác dụng rồi nối với đoạn đó bằng một chi tiết cụ thể (nhân vật đã thấy gì, cảm thấy gì)."],
    },
  ],
  doiChieu: [
    ["Ngôi kể", "Vị trí của người kể: đứng trong truyện (xưng tôi) hay đứng ngoài (gọi tên nhân vật)"],
    ["Người kể chuyện", "Người đứng ra kể, có thể là một nhân vật hoặc một người giấu mặt"],
    ["Ngôi thứ nhất", "Người kể xưng “tôi”, là nhân vật trong truyện"],
    ["Ngôi thứ ba", "Người kể giấu mặt, gọi nhân vật bằng tên"],
    ["Điểm nhìn", "Câu chuyện được nhìn qua con mắt của ai"],
  ],
  meo: "Xưng TÔI là ngôi MỘT, gọi TÊN là ngôi BA. Tác dụng thì nhớ hai chữ: ngôi một CHÂN THỰC (kể được cảm xúc của chính mình), ngôi ba BAO QUÁT (kể được nhiều người, nhiều nơi).",
  tuKiemTra: [
    { q: "“Đi lấy mật” kể theo ngôi nào? Dấu hiệu?", a: "Ngôi thứ nhất. Người kể là An, xưng “tôi” và trực tiếp tham gia chuyến đi lấy mật." },
    { q: "“Bầy chim chìa vôi” kể theo ngôi nào? Dấu hiệu?", a: "Ngôi thứ ba. Người kể không xuất hiện, gọi nhân vật bằng tên Mên, Mon." },
    { q: "Đoạn: “Tôi ngồi thu lu trên bến, nhìn con đò của bố khuất dần sau khúc sông. Trời lạnh lắm, mà tôi không dám về.” Ngôi kể nào? Tác dụng?", a: "Ngôi thứ nhất (xưng tôi). Tác dụng: người kể trực tiếp bộc lộ được cảm xúc của mình (lạnh nhưng không dám về vì lo cho bố), khiến câu chuyện chân thực, gần gũi." },
    { q: "Đoạn: “Thằng Tí lùi lại một bước. Nó biết mẹ đang nhìn nó từ trong bếp, nhưng nó không quay đầu.” Ngôi kể nào? Vì sao?", a: "Ngôi thứ ba, vì người kể gọi nhân vật là “thằng Tí”, “nó” và biết cả suy nghĩ của Tí lẫn hành động của mẹ Tí." },
    { q: "Câu “– Em sợ lắm anh ạ.” có xưng “em”, vậy truyện kể theo ngôi thứ nhất đúng không?", a: "Không chắc. Đó là lời nhân vật nói trong đối thoại. Phải nhìn vào phần lời kể bên ngoài: nếu lời kể gọi nhân vật bằng tên thì vẫn là ngôi thứ ba." },
    { q: "Nếu “Bầy chim chìa vôi” được Mon kể lại theo ngôi thứ nhất, câu chuyện sẽ khác đi thế nào?", a: "Ta sẽ nghe rõ nỗi lo và cảm xúc của Mon, nhưng không còn biết Mên nghĩ gì trong lòng và cũng khó tả được cảnh bãi sông từ xa. Truyện sẽ thân mật hơn nhưng kém bao quát." },
  ],
};

/* ===== Thứ Tư 23/09 · Đề tài và chi tiết tiêu biểu ===== */
window.KIM_GIANG["on-van-0923"] = {
  mon: "van",
  ngay: "2026-09-23",
  tieuDe: "Ôn Văn ngày 2 · Đề tài và chi tiết tiêu biểu trong truyện",
  sgk: "Ngữ văn 7 tập 1, Tri thức ngữ văn Bài 1 (tr. 10)",
  motCau: "Đề tài là câu trả lời cho câu hỏi “truyện này viết VỀ CÁI GÌ?”, nói gọn trong vài chữ. Chi tiết tiêu biểu là những hình ảnh, lời nói, việc làm nhỏ mà bỏ đi thì truyện mất hay, mất ý. Hai câu hỏi này gần như đề nào cũng có, và cách trả lời rất ngắn.",
  phan: [
    {
      ten: "Đề tài: trả lời bằng một cụm danh từ",
      doan: ["Cách tìm: hỏi “truyện kể về ai, về chuyện gì trong cuộc sống?”, rồi rút gọn thành một cụm từ. Không kể lại truyện, không nêu bài học ở câu này."],
      kn: [
        { ten: "Bầy chim chìa vôi", de: "Kể về hai anh em Mên, Mon lo cho tổ chim non trong đêm mưa lũ.",
          vd: "Đề tài: tuổi thơ và tình yêu thương loài vật (hoặc: trẻ em với thế giới tự nhiên)." },
        { ten: "Đi lấy mật", de: "Kể về chuyến đi vào rừng U Minh lấy mật ong của An cùng tía nuôi và Cò.",
          vd: "Đề tài: thiên nhiên và cuộc sống con người ở rừng U Minh (hoặc: tuổi thơ gắn với thiên nhiên Nam Bộ)." },
        { ten: "Một đoạn trích lạ", de: "Nhìn xem nhân vật là ai (trẻ em, người mẹ, người lính…) và chuyện xoay quanh điều gì (tình bạn, gia đình, chiến tranh, lao động…). Ghép hai thứ lại.",
          vd: "Truyện về một cậu bé nhặt ve chai nuôi em → đề tài: tình anh em / cuộc sống của trẻ em nghèo." },
      ],
      hop: { nhan: "Phân biệt cho khỏi mất điểm", chu: "Đề tài là VỀ CÁI GÌ (vài chữ). Chủ đề hay thông điệp là MUỐN NÓI ĐIỀU GÌ (một câu). Bài học là MÌNH RÚT RA ĐƯỢC GÌ (một câu, có chữ “cần”, “nên”). Đề hỏi đề tài mà viết cả câu bài học thì thầy cô sẽ trừ điểm vì trả lời sai câu hỏi." },
    },
    {
      ten: "Chi tiết tiêu biểu: nhỏ mà không bỏ được",
      doan: ["Sách định nghĩa: chi tiết tiêu biểu là chi tiết gây ấn tượng, xúc động, góp phần làm nổi bật nhân vật hoặc chủ đề. Cách thử: che chi tiết đó đi, nếu truyện nhạt hẳn hoặc không còn hiểu nhân vật thì đó là chi tiết tiêu biểu."],
      buoc: [
        { so: 1, ten: "Tìm", de: "Nhìn vào ba chỗ: việc nhân vật làm, lời nhân vật nói, và hình ảnh được tả kĩ nhất.",
          vd: "Bầy chim chìa vôi: hai anh em đội mưa ra sông giữa đêm; cảnh bầy chim non bay lên khỏi mặt nước lúc bình minh; hai anh em đứng nhìn mà khóc lúc nào không hay." },
        { so: 2, ten: "Nêu", de: "Chép lại chi tiết bằng lời ngắn, có thể trích vài chữ trong ngoặc kép.",
          vd: "Chi tiết hai anh em “khóc lúc nào không biết” khi thấy bầy chim bay lên." },
        { so: 3, ten: "Nói vì sao tiêu biểu", de: "Một câu: chi tiết đó cho thấy điều gì ở nhân vật hoặc ở ý nghĩa truyện.",
          vd: "Giọt nước mắt ấy là niềm vui và nỗi xúc động khi bầy chim thoát chết, cho thấy tấm lòng yêu thương loài vật trong trẻo của hai đứa trẻ." },
      ],
      hop: { nhan: "Mẫu câu", chu: "Chi tiết tiêu biểu: “…”. Chi tiết này cho thấy … (tính cách / tình cảm của nhân vật), qua đó làm nổi bật … (ý nghĩa truyện). Hai câu là đủ điểm." },
    },
    {
      ten: "Đọc một chi tiết ra ý nghĩa: đi qua ba tầng",
      doan: ["Lỗi hay gặp nhất là chép lại chi tiết rồi dừng. Điểm nằm ở phần Kim giải thích chi tiết đó NÓI LÊN ĐIỀU GÌ. Gặp chi tiết nào, Kim tự hỏi lần lượt ba câu dưới đây, câu sau sâu hơn câu trước."],
      buoc: [
        { so: 1, ten: "Tầng 1 · Nhân vật đang làm gì, nói gì?", de: "Kể lại ngắn gọn đúng điều đang diễn ra, chưa thêm ý.",
          vd: "Giữa đêm, Mon thức dậy gọi anh, hai anh em nói chuyện với nhau về tổ chim chìa vôi ngoài bãi cát." },
        { so: 2, ten: "Tầng 2 · Việc đó cho thấy gì ở nhân vật?", de: "Gọi tên tình cảm, tính cách hoặc mối quan hệ giữa các nhân vật. Lấy từ trong bảng từ ở phần sau.",
          vd: "Có nỗi lo, Mon tìm đến anh đầu tiên, còn Mên cũng chưa ngủ và nghe em nói. Hai anh em tin cậy nhau, chia sẻ với nhau cả nỗi lo; anh là chỗ dựa của em." },
        { so: 3, ten: "Tầng 3 · Chi tiết giúp gì cho câu chuyện?", de: "Nó làm nổi bật nhân vật hoặc chủ đề, tạo không khí, gây cảm xúc cho người đọc, hay dẫn tới sự việc tiếp theo.",
          vd: "Cuộc trò chuyện trong đêm mở ra cả câu chuyện, dẫn tới việc hai anh em ra bãi sông. Người đọc thấy tình yêu loài vật ở trẻ em xuất phát từ tấm lòng, không ai bắt." },
      ],
      hop: { nhan: "Viết thành câu trả lời", chu: "Chi tiết “…” cho thấy … (tầng 2). Qua đó, chi tiết góp phần … (tầng 3). Nhiều bạn chỉ viết tầng 1 nên mất điểm. Tầng 2 là phần chính, tầng 3 làm câu trả lời trọn vẹn." },
    },
    {
      ten: "Mỗi loại chi tiết thường nói lên điều gì",
      doan: ["Không cần đoán mò. Mỗi loại chi tiết thường mở ra một kiểu ý nghĩa quen thuộc. Gặp đoạn trích lạ, Kim xem chi tiết thuộc loại nào rồi hướng câu trả lời theo gợi ý dưới đây."],
      kn: [
        { ten: "Lời trò chuyện giữa các nhân vật", de: "Cho thấy quan hệ và tình cảm giữa họ: thân thiết hay xa cách, quan tâm, tin cậy, che chở nhau. Cách xưng hô và giọng nói (dịu dàng, gắt gỏng, thì thầm) cũng là dấu hiệu.",
          vd: "Hai anh em nói chuyện giữa đêm, em hỏi, anh đáp → tình anh em gắn bó, em tin anh, anh che chở em." },
        { ten: "Hành động, việc làm", de: "Cho thấy phẩm chất: dũng cảm, có trách nhiệm, tốt bụng, hay ích kỉ… Việc càng khó, càng nguy hiểm thì phẩm chất càng hiện rõ.",
          vd: "Chèo đò ra sông giữa đêm khi nước đang lên → dũng cảm, dám làm để cứu bầy chim chứ không chỉ lo suông." },
        { ten: "Cử chỉ, nét mặt, giọt nước mắt", de: "Cho thấy cảm xúc sâu bên trong mà nhân vật không nói thành lời.",
          vd: "Hai anh em khóc khi thấy bầy chim bay lên → vui mừng, xúc động, nhẹ nhõm vì bầy chim thoát nạn." },
        { ten: "Suy nghĩ, nỗi lo trong lòng nhân vật", de: "Cho thấy tâm hồn: nhạy cảm, giàu lòng thương, biết nghĩ cho người khác và cho con vật.",
          vd: "Mon lo tổ chim bị nước cuốn đến mất ngủ → tâm hồn trong trẻo, giàu tình thương." },
        { ten: "Cảnh thiên nhiên, thời tiết, thời gian", de: "Tạo không khí cho câu chuyện, làm nền cho tâm trạng nhân vật, hoặc làm tăng thử thách mà nhân vật phải vượt qua.",
          vd: "Đêm tối, nước sông dâng → căng thẳng, nguy hiểm, làm việc làm của hai đứa trẻ thêm đáng quý. Cảnh bình minh lúc kết → mở ra niềm vui và hi vọng." },
        { ten: "Hình ảnh được tả kĩ nhất", de: "Thường mang ý nghĩa lớn của truyện, là điều tác giả muốn người đọc nhớ mãi.",
          vd: "Bầy chim non bay lên khỏi bãi cát đang ngập nước → hình ảnh của sự sống và sức vươn lên." },
      ],
      hop: { nhan: "Bảng từ để gọi tên ở tầng 2 và tầng 3", chu: "Tình cảm: yêu thương, quan tâm, lo lắng, gắn bó, tin cậy, che chở, nhường nhịn, biết ơn. Phẩm chất: dũng cảm, có trách nhiệm, tốt bụng, nhân hậu, kiên trì, hồn nhiên, trong sáng. Cảm xúc: vui sướng, xúc động, hồi hộp, lo âu, nhẹ nhõm, ân hận. Tác dụng với truyện: làm nổi bật nhân vật, làm nổi bật chủ đề, tạo không khí, tạo sự hồi hộp, gây xúc động cho người đọc, dẫn tới sự việc tiếp theo." },
    },
    {
      ten: "Bầy chim chìa vôi: từng chi tiết nói lên điều gì",
      doan: ["Mỗi dòng dưới đây gồm chi tiết, điều chi tiết cho thấy (tầng 2) và tác dụng với câu chuyện (tầng 3). Kim đọc to từng dòng, rồi che phần giải thích đi và thử tự nói lại."],
      kn: [
        { ten: "Mon thức giấc giữa đêm, gọi anh để hỏi về tổ chim", de: "Cho thấy Mon nhạy cảm, lo cho bầy chim đến mất ngủ. Em tìm đến anh vì tin anh sẽ hiểu và giúp mình.",
          vd: "Tác dụng: mở đầu câu chuyện tự nhiên; người đọc thấy nỗi lo xuất phát từ tấm lòng của một đứa trẻ." },
        { ten: "Hai anh em nói chuyện với nhau trong đêm", de: "Cho thấy tình anh em thân thiết, gắn bó. Có chuyện gì hai anh em cũng chia sẻ với nhau, cùng lo và cùng tìm cách.",
          vd: "Tác dụng: những câu hỏi đáp ngắn, qua lại làm cảnh đêm khuya sống động; người đọc như ngồi cạnh hai anh em và cảm được tình cảm giữa họ." },
        { ten: "Mên cũng chưa ngủ, cũng lo cho bầy chim như em", de: "Cho thấy hai anh em cùng chung một tấm lòng. Mên là anh nên đứng ra cùng em làm, không để em lo một mình.",
          vd: "Tác dụng: làm nổi bật tình anh em đồng lòng, che chở nhau; người anh là chỗ dựa cho em." },
        { ten: "Hai anh em chèo đò ra bãi cát giữa sông lúc nước đang lên", de: "Cho thấy lòng dũng cảm và tình thương có hành động thật. Đi cùng nhau nên hai anh em cũng dựa vào nhau, bảo vệ nhau trước nguy hiểm.",
          vd: "Tác dụng: đẩy câu chuyện lên đoạn hồi hộp nhất; người đọc lo cho hai đứa trẻ và càng quý tấm lòng của chúng." },
        { ten: "Cảnh đêm tối, nước sông dâng cao, bãi cát sắp ngập", de: "Cho thấy bầy chim non đang gặp nguy thật sự, và đây là thử thách lớn với hai đứa trẻ.",
          vd: "Tác dụng: tạo không khí căng thẳng, làm nền để việc làm của Mên và Mon thêm đáng quý." },
        { ten: "Bầy chim non gắng sức bay lên khỏi bãi cát đang chìm, trong ánh bình minh", de: "Cho thấy sức sống mạnh mẽ của những sinh linh bé nhỏ; bầy chim đã tự vượt qua hiểm nguy.",
          vd: "Tác dụng: đây là hình ảnh đẹp nhất truyện, nói về sự sống và niềm hi vọng; khép lại nỗi lo bằng niềm vui." },
        { ten: "Hai anh em khóc lúc nào không biết", de: "Cho thấy niềm vui và sự xúc động trào ra thành nước mắt; tình thương loài vật trong trẻo, chân thành.",
          vd: "Tác dụng: tạo cái kết lắng đọng, người đọc cũng xúc động theo; làm nổi bật chủ đề yêu thương loài vật." },
      ],
    },
    {
      ten: "Đi lấy mật: đọc thử vài chi tiết",
      kn: [
        { ten: "Tía nuôi dặn dò An cách đi rừng", de: "Cho thấy tía thương An, quan tâm và muốn truyền lại kinh nghiệm sống ở rừng cho con.",
          vd: "Tác dụng: làm nổi bật tình cảm gia đình ấm áp dù là cha nuôi, và vốn hiểu biết của người dân U Minh." },
        { ten: "Cò chỉ cho An cách nhìn ong bay để tìm tổ", de: "Cho thấy Cò thạo rừng, và hai đứa trẻ thân thiết, sẵn lòng chỉ bảo nhau.",
          vd: "Tác dụng: cho thấy trẻ em ở U Minh lớn lên cùng rừng; câu chuyện thêm gần gũi, vui tươi." },
        { ten: "Người U Minh gác kèo để ong tự đến làm tổ", de: "Cho thấy người dân hiểu tập tính loài ong, biết sống hòa hợp với thiên nhiên.",
          vd: "Tác dụng: làm nổi bật trí khôn, kinh nghiệm của con người nơi đây và vẻ đẹp của cuộc sống gắn với rừng." },
        { ten: "Cảnh rừng U Minh buổi sáng hiện lên qua mắt An", de: "Cho thấy An tò mò, thích thú, có tâm hồn nhạy cảm với cái đẹp.",
          vd: "Tác dụng: vẽ nên bức tranh thiên nhiên Nam Bộ tươi đẹp, trù phú; kể qua mắt một cậu bé nên cảnh thêm sống động." },
      ],
    },
  ],
  doiChieu: [
    ["Đề tài", "Truyện viết về cái gì (một cụm từ)"],
    ["Chủ đề", "Điều truyện muốn nói (một câu)"],
    ["Chi tiết", "Một hình ảnh, lời nói hay việc làm nhỏ trong truyện"],
    ["Chi tiết tiêu biểu", "Chi tiết mà bỏ đi thì truyện nhạt hẳn, không còn hiểu rõ nhân vật"],
    ["Chi tiết cho thấy…", "Nói ra tình cảm, tính cách, mối quan hệ của nhân vật mà chi tiết để lộ"],
    ["Tác dụng của chi tiết", "Chi tiết giúp gì cho truyện: làm nổi bật nhân vật, chủ đề, tạo không khí, gây xúc động"],
    ["Nhân vật", "Người (hoặc con vật, đồ vật) làm nên câu chuyện"],
    ["Cốt truyện", "Chuỗi sự việc chính theo thứ tự"],
  ],
  meo: "Đề tài: hỏi VỀ GÌ, đáp bằng CỤM TỪ. Chi tiết tiêu biểu: CHE ĐI mà truyện NHẠT thì đúng là nó. Đọc chi tiết qua ba tầng: làm gì, nói gì → cho thấy tình cảm, tính cách gì → giúp gì cho câu chuyện.",
  tuKiemTra: [
    { q: "Nêu đề tài của truyện “Bầy chim chìa vôi”.", a: "Tuổi thơ và tình yêu thương loài vật (hoặc: trẻ em với thế giới thiên nhiên). Trả lời bằng cụm từ, không kể chuyện." },
    { q: "Nêu đề tài của “Đi lấy mật”.", a: "Thiên nhiên và cuộc sống của con người ở rừng U Minh (tuổi thơ gắn với thiên nhiên Nam Bộ)." },
    { q: "Bạn Lan trả lời “Đề tài của Bầy chim chìa vôi là chúng ta cần yêu thương loài vật”. Lan sai ở đâu?", a: "Lan viết bài học chứ không phải đề tài. Đề tài chỉ nói truyện viết về cái gì, không nói ta cần làm gì." },
    { q: "Nêu một chi tiết tiêu biểu trong “Bầy chim chìa vôi” và cho biết chi tiết đó thể hiện điều gì.", a: "Ví dụ: hai anh em đội mưa chèo đò ra bãi cát giữa đêm chỉ vì lo cho tổ chim. Chi tiết cho thấy tấm lòng yêu thương loài vật và sự dũng cảm của hai đứa trẻ." },
    { q: "Vì sao chi tiết hai anh em “khóc lúc nào không biết” được coi là tiêu biểu?", a: "Vì đó là giây phút xúc động nhất truyện: nước mắt của niềm vui khi bầy chim thoát chết, làm nổi bật tâm hồn trong trẻo, giàu tình thương của Mên và Mon. Bỏ chi tiết này đi, truyện mất đi cái kết đẹp." },
    { q: "Đoạn trích lạ kể về một bà cụ ngày nào cũng ra bến xe chờ con trai đi bộ đội chưa về. Đề tài là gì? Một chi tiết tiêu biểu có thể là gì?", a: "Đề tài: tình mẫu tử (nỗi chờ đợi của người mẹ). Chi tiết tiêu biểu: việc bà cụ ngày nào cũng ra bến xe chờ, cho thấy tình thương con bền bỉ." },
    { q: "Chi tiết Mon thức dậy giữa đêm gọi anh để hỏi về tổ chim cho thấy điều gì về tình anh em?", a: "Mon tin anh, có nỗi lo là tìm đến anh đầu tiên; Mên sẵn lòng nghe và cùng em tìm cách. Hai anh em gắn bó, chia sẻ và che chở cho nhau." },
    { q: "Cảnh đêm tối, nước sông đang dâng trong “Bầy chim chìa vôi” có tác dụng gì?", a: "Tạo không khí căng thẳng, cho thấy bầy chim gặp nguy thật sự, qua đó làm nổi bật lòng dũng cảm và tình thương của hai anh em." },
    { q: "Bạn Minh trả lời: “Chi tiết tiêu biểu là hai anh em chèo đò ra bãi cát giữa đêm.” rồi dừng. Minh còn thiếu gì?", a: "Minh mới ở tầng 1 (kể lại). Cần thêm tầng 2: chi tiết cho thấy lòng dũng cảm và tình yêu loài vật của hai anh em. Và tầng 3: chi tiết làm câu chuyện hồi hộp, làm nổi bật chủ đề." },
    { q: "Đoạn trích lạ: “Chị Hoa cởi chiếc áo khoác quàng cho em, còn mình thì run lên vì lạnh.” Chi tiết này cho thấy điều gì, có tác dụng gì?", a: "Chị nhường áo cho em dù bản thân đang lạnh → chị thương em, biết che chở, nhường nhịn. Tác dụng: làm nổi bật tình chị em và gây xúc động cho người đọc." },
  ],
};

/* ===== Thứ Năm 24/09 · Nhân vật và bài học rút ra ===== */
window.KIM_GIANG["on-van-0924"] = {
  mon: "van",
  ngay: "2026-09-24",
  tieuDe: "Ôn Văn ngày 3 · Nhận xét nhân vật và rút ra bài học",
  sgk: "Ngữ văn 7 tập 1, Bài 1 · Bầy chim chìa vôi, Đi lấy mật",
  motCau: "Hai câu cuối phần đọc hiểu thường là: “Em nhận xét gì về nhân vật …?” và “Từ văn bản, em rút ra bài học gì?”. Đây là hai câu được điểm cao nhất trong phần đọc hiểu (thường 1 điểm mỗi câu) và cũng là hai câu Kim hay viết ngắn quá. Hôm nay học cách viết đủ ý mà không dài.",
  phan: [
    {
      ten: "Nhận xét nhân vật: đi từ việc làm đến tính cách",
      doan: ["Người kể hiếm khi nói thẳng “Mên là người tốt bụng”. Kim phải tự suy ra từ ba chỗ: nhân vật LÀM gì, NÓI gì, và NGHĨ gì. Mỗi việc làm gợi ra một nét tính cách."],
      buoc: [
        { so: 1, ten: "Nhặt việc làm, lời nói", de: "Tìm 2 chi tiết về nhân vật được hỏi.",
          vd: "Mên: gắt em “Có ngủ đi không?” nhưng rồi vẫn dậy đi cùng; một mình gò lưng kéo đò về bến; dẫn em lên bờ đứng chờ trời sáng." },
        { so: 2, ten: "Gọi tên tính cách", de: "Mỗi chi tiết ứng với một từ chỉ tính cách. Chọn từ trong kho ở dưới.",
          vd: "Gắt nhưng vẫn đi → bề ngoài cộc cằn nhưng thương em, thương chim. Kéo đò một mình → mạnh mẽ, có trách nhiệm của người anh." },
        { so: 3, ten: "Viết thành 2–3 câu", de: "Câu 1: nhận xét chung. Câu 2: dẫn chi tiết. Câu 3: cảm nghĩ hoặc điều em học được từ nhân vật.",
          vd: "Mên là một người anh mạnh mẽ và giàu tình thương. Tuy hay gắt gỏng với em nhưng cậu vẫn đội mưa đi cứu bầy chim và một mình kéo đò về bến. Em rất quý sự cứng cỏi mà ấm áp ấy của Mên." },
      ],
      hop: { nhan: "Kho từ chỉ tính cách", chu: "Tốt bụng, giàu tình thương, nhân hậu, dũng cảm, kiên trì, có trách nhiệm, hiếu thảo, tinh tế, hồn nhiên, tò mò ham hiểu biết, chăm chỉ, khéo léo, từng trải, hiền hậu, cộc cằn bề ngoài nhưng ấm áp bên trong. Chọn 2 từ khớp với chi tiết, đừng liệt kê cả kho." },
    },
    {
      ten: "Bài học rút ra: viết theo công thức “cần … vì …”",
      doan: ["Bài học là điều Kim tự nhắc mình sau khi đọc. Muốn đủ điểm, cần hai vế: NÊN LÀM GÌ và VÌ SAO (nối với truyện). Nếu đề cho 1 điểm thì viết 2 bài học, mỗi bài học một câu."],
      buoc: [
        { so: 1, ten: "Nhìn vào việc tốt nhân vật đã làm", de: "Việc tốt đó gợi ra điều ta nên học.",
          vd: "Mên, Mon cứu chim → cần biết yêu thương, bảo vệ loài vật." },
        { so: 2, ten: "Thêm vế “vì” nối với truyện", de: "Giải thích bằng chính câu chuyện.",
          vd: "…vì mỗi sinh vật nhỏ bé đều đáng được sống, như bầy chim non đã bay lên trong niềm vui của hai anh em." },
        { so: 3, ten: "Bài học thứ hai lấy từ góc khác", de: "Tình cảm giữa các nhân vật, hoặc cách nhân vật đối mặt khó khăn.",
          vd: "Anh em cần yêu thương, đùm bọc nhau, vì Mên dù gắt gỏng vẫn không để Mon đi một mình trong đêm mưa." },
      ],
      hop: { nhan: "Mẫu câu bài học", chu: "Qua văn bản, em rút ra bài học: cần … (việc nên làm), bởi … (lí do gắn với truyện). Bên cạnh đó, em cũng hiểu rằng … (bài học thứ hai). Hai câu, đủ điểm." },
    },
    {
      ten: "Đi lấy mật: luyện thêm với An",
      doan: ["An là cậu bé thành phố lần đầu vào rừng. Chi tiết: An nhìn ngắm rừng buổi sáng không chớp mắt; hỏi Cò cách tìm ong; nhớ lời má nuôi kể về gác kèo; so sánh cách lấy mật của người U Minh với sách đã đọc. Tính cách: tò mò, ham hiểu biết, yêu thiên nhiên, biết quan sát và suy nghĩ. Bài học: cần biết quan sát và học hỏi từ cuộc sống quanh mình; cần sống hòa hợp, trân trọng thiên nhiên như cách người dân U Minh lấy mật mà không phá tổ ong."],
    },
    {
      ten: "Từ chi tiết đọc ra tính cách và tình cảm: luyện với truyện ngoài sách",
      doan: ["Đề kiểm tra hay lấy truyện ngoài sách. Cách làm không đổi: nhặt chi tiết, hỏi chi tiết đó cho thấy gì ở nhân vật, rồi gọi tên tính cách, tình cảm. Dưới đây là mấy truyện Kim đã học ở lớp 6 hoặc có thể gặp trong đề."],
      kn: [
        { ten: "Bài học đường đời đầu tiên (Tô Hoài): Dế Mèn đứng lặng giờ lâu trước nấm mồ Dế Choắt", de: "Cho thấy Mèn ân hận, đau xót, đã nhận ra lỗi lầm do thói kiêu căng, xốc nổi của mình.",
          vd: "Tác dụng: đây là lúc nhân vật thay đổi; chi tiết làm nổi bật bài học về sự kiêu ngạo. Bài học: cần khiêm tốn, nghĩ trước khi làm, vì một phút xốc nổi có thể gây hại cho người khác." },
        { ten: "Cô bé bán diêm (An-đéc-xen): mỗi lần quẹt diêm, em bé thấy lò sưởi, bàn ăn, cây thông Nô-en, rồi thấy bà", de: "Mỗi hình ảnh là một mong ước: được sưởi ấm, được no, được vui như bao đứa trẻ khác. Hình ảnh người bà cho thấy điều em khao khát nhất là được yêu thương.",
          vd: "Tác dụng: đặt ảo ảnh ấm áp cạnh thực tế lạnh giá khiến người đọc càng thương em bé; bộc lộ lòng thương cảm của nhà văn với trẻ em nghèo." },
        { ten: "Chiếc lá cuối cùng (O. Hen-ri): cụ Bơ-men lặng lẽ vẽ chiếc lá lên tường trong đêm mưa gió", de: "Cho thấy tình thương và sự hi sinh thầm lặng. Cụ làm mà không nói với ai, chỉ mong cô gái đang ốm nặng tìm lại niềm tin để sống.",
          vd: "Tác dụng: tạo bất ngờ ở cuối truyện và làm nổi bật ý nghĩa: tình người có thể cứu sống một con người." },
        { ten: "Bức tranh của em gái tôi (Tạ Duy Anh): người anh sững sờ trước bức tranh em gái vẽ mình rất đẹp", de: "Em gái vẫn vẽ anh đẹp dù anh từng ghen tị, xa lánh em → em nhân hậu, bao dung. Người anh lặng đi → xấu hổ, hối hận, nhận ra mình chưa tốt.",
          vd: "Tác dụng: đây là chỗ người anh thay đổi; chi tiết làm nổi bật tình anh em và bài học về lòng ghen tị." },
      ],
    },
    {
      ten: "Chi tiết đời thường: tự đặt để luyện",
      doan: ["Những chi tiết này rất hay gặp trong truyện về gia đình, bạn bè. Kim đọc chi tiết, che phần giải thích, tự nói “chi tiết cho thấy…” rồi mới mở ra xem."],
      kn: [
        { ten: "Bữa cơm, mẹ gắp miếng cá ngon nhất cho con, còn mình ăn phần đầu đuôi", de: "Cho thấy mẹ thương con, luôn nhường phần tốt nhất cho con, hi sinh lặng lẽ mà không nói ra.",
          vd: "Hợp với đề về tình mẫu tử, lòng biết ơn cha mẹ." },
        { ten: "Bố không nói gì, chỉ lặng lẽ nhét chiếc áo mưa vào cặp con", de: "Cho thấy bố quan tâm con từng chút, yêu thương mà không nói thành lời.",
          vd: "Hợp với đề về tình cha con, về những yêu thương thầm lặng." },
        { ten: "Hai bạn giận nhau, hôm sau một bạn vẫn để phần cái bánh cho bạn kia", de: "Cho thấy bạn ấy bao dung, trân trọng tình bạn hơn cơn giận.",
          vd: "Hợp với đề về tình bạn, lòng vị tha." },
        { ten: "Thấy em ngã, người anh vứt cặp chạy lại đỡ, phủi đất cho em rồi cõng em về", de: "Cho thấy anh thương em, chu đáo, có trách nhiệm; lo cho em hơn cả đồ của mình.",
          vd: "Hợp với đề về tình anh em; giống cách Mên không để Mon một mình." },
      ],
      hop: { nhan: "Chi tiết lặng lẽ thường nói nhiều nhất", chu: "Những việc nhân vật làm mà không nói ra (gắp thức ăn, đứng lặng, lặng lẽ vẽ, để phần) thường cho thấy tình cảm sâu sắc. Gặp các chữ “lặng lẽ”, “im lặng”, “đứng lặng”, “không nói gì” trong đề, Kim chú ý ngay: đó rất có thể là chi tiết tiêu biểu." },
    },
  ],
  doiChieu: [
    ["Nhận xét nhân vật", "Nói nhân vật là người thế nào, dựa vào việc làm và lời nói của họ"],
    ["Tính cách", "Nét bên trong lâu dài của một người: tốt bụng, dũng cảm, cộc cằn…"],
    ["Hành động", "Việc nhân vật làm, là bằng chứng để suy ra tính cách"],
    ["Bài học rút ra", "Điều mình tự nhắc sẽ làm sau khi đọc, có chữ cần / nên"],
    ["Thông điệp", "Điều tác giả muốn gửi tới người đọc, gần giống bài học nhưng nói từ phía tác giả"],
  ],
  meo: "Nhận xét nhân vật: VIỆC LÀM trước, TÍNH CÁCH sau, không nói suông. Bài học: CẦN gì + VÌ sao, và luôn viết HAI bài học nếu câu đó 1 điểm.",
  tuKiemTra: [
    { q: "Nhận xét về nhân vật Mon trong “Bầy chim chìa vôi” (2–3 câu).", a: "Mon là cậu bé giàu lòng thương và rất nhạy cảm. Giữa đêm mưa, Mon không ngủ được vì lo tổ chim chìa vôi bị ngập, rồi nằng nặc đòi anh ra sông cứu chim. Tấm lòng trong trẻo của Mon khiến em xúc động." },
    { q: "Vì sao có thể nói Mên “cộc cằn bề ngoài nhưng ấm áp bên trong”?", a: "Vì Mên gắt em “Có ngủ đi không?”, nhưng rồi vẫn dậy đi cùng, một mình kéo đò về bến và dẫn em lên bờ. Lời nói thì gắt, việc làm thì đầy yêu thương." },
    { q: "Rút ra hai bài học từ “Bầy chim chìa vôi”, mỗi bài học một câu có vế “vì”.", a: "Cần yêu thương và bảo vệ loài vật, vì mỗi sinh vật nhỏ bé đều đáng được sống như bầy chim non trong truyện. Anh em cần đùm bọc nhau, vì Mên dù gắt gỏng vẫn không để Mon đi một mình trong đêm mưa." },
    { q: "Bạn Nam viết bài học: “Em sẽ cố gắng học tốt.” Sao câu này không được điểm?", a: "Vì không liên quan đến truyện và không có vế lí do. Bài học phải rút ra từ việc nhân vật đã làm và nối với nội dung văn bản." },
    { q: "Nhận xét về nhân vật An trong “Đi lấy mật”.", a: "An là cậu bé tò mò, ham hiểu biết và yêu thiên nhiên. Lần đầu vào rừng, An say sưa ngắm cảnh, hỏi Cò cách tìm ong, và tự so sánh điều mình thấy với điều đã đọc trong sách. Cách quan sát tinh tế của An làm rừng U Minh hiện lên rất sống động." },
    { q: "Từ cách người dân U Minh lấy mật mà không phá tổ ong, em rút ra bài học gì?", a: "Cần sống hòa hợp và biết trân trọng thiên nhiên, vì lấy của rừng mà vẫn giữ cho rừng thì con người mới có mật ong mãi về sau." },
    { q: "Chi tiết mẹ gắp miếng cá ngon nhất cho con, còn mình ăn phần đầu đuôi cho thấy điều gì về người mẹ?", a: "Mẹ thương con, luôn nhường phần tốt nhất cho con, hi sinh lặng lẽ mà không cần nói ra." },
    { q: "Trong “Cô bé bán diêm”, lần quẹt diêm cuối em bé thấy bà. Chi tiết ấy cho thấy điều gì?", a: "Điều em khao khát nhất không phải là cái ăn, cái mặc mà là tình thương. Chi tiết khiến người đọc xót xa và thấy được lòng thương cảm của nhà văn với em bé." },
    { q: "Đọc: “Thấy em ngã, Tuấn vứt cặp chạy lại đỡ, phủi đất trên đầu gối em rồi cõng em về.” Nhận xét về Tuấn (2 câu).", a: "Tuấn là người anh thương em, chu đáo và có trách nhiệm. Việc Tuấn vứt cặp chạy lại đỡ, phủi đất rồi cõng em về cho thấy anh lo cho em hơn cả đồ của mình." },
  ],
};

/* ===== Thứ Sáu 25/09 · So sánh ===== */
window.KIM_GIANG["on-van-0925"] = {
  mon: "van",
  ngay: "2026-09-25",
  tieuDe: "Ôn Văn ngày 4 · Biện pháp tu từ so sánh và cách nêu tác dụng",
  sgk: "Ôn lại kiến thức lớp 6 (Ngữ văn 6 tập 1, Bài 3) · dùng trong đề đọc hiểu",
  motCau: "So sánh là đem một thứ đặt cạnh một thứ khác giống nó ở điểm nào đó, để người đọc hình dung rõ hơn. Câu hỏi trong đề luôn có hai phần: CHỈ RA (biện pháp gì, ở chữ nào) và NÊU TÁC DỤNG. Phần chỉ ra Kim làm tốt rồi, hôm nay tập trung vào phần tác dụng, vì đó là chỗ mất điểm nhiều nhất.",
  phan: [
    {
      ten: "Nhận diện: bốn bộ phận của một phép so sánh",
      doan: ["Ví dụ: “Mặt trời đỏ rực như một quả cầu lửa.”"],
      kn: [
        { ten: "Vế A (cái được so sánh)", de: "Thứ đang nói tới.", vd: "mặt trời" },
        { ten: "Phương diện so sánh", de: "Giống nhau ở chỗ nào. Có thể vắng.", vd: "đỏ rực" },
        { ten: "Từ so sánh", de: "như, tựa, giống, là, bao nhiêu… bấy nhiêu, chẳng bằng, hơn.", vd: "như" },
        { ten: "Vế B (cái dùng để so sánh)", de: "Thứ đem ra ví.", vd: "một quả cầu lửa" },
      ],
      hop: { nhan: "Bẫy chữ “là”", chu: "“Mẹ là cô giáo” không phải so sánh, vì mẹ đúng là cô giáo thật. “Mẹ là ngọn gió của con suốt đời” mới là so sánh, vì mẹ không phải gió thật, tác giả chỉ ví. Thử hỏi: vế B có thật là vế A không? Không thì là so sánh." },
    },
    {
      ten: "Nêu tác dụng: công thức hai tầng",
      doan: ["Tác dụng luôn gồm hai tầng. Tầng 1 là tác dụng chung (câu học thuộc). Tầng 2 là tác dụng riêng trong câu đang hỏi (Kim tự viết). Thiếu tầng 2 chỉ được nửa điểm."],
      buoc: [
        { so: 1, ten: "Tầng 1 · câu học thuộc", de: "Phép so sánh giúp sự vật được miêu tả trở nên cụ thể, sinh động, gợi hình, gợi cảm hơn.",
          vd: "Chép nguyên câu này vào bài." },
        { so: 2, ten: "Tầng 2 · nối với câu cụ thể", de: "Trả lời: nhờ ví A với B, người đọc hình dung A ra sao? Tác giả bộc lộ tình cảm gì?",
          vd: "So sánh mặt trời với quả cầu lửa giúp người đọc hình dung mặt trời lúc hoàng hôn to tròn, đỏ và rực rỡ, đồng thời cho thấy sự say mê của tác giả trước cảnh chiều." },
        { so: 3, ten: "Ghép thành câu trả lời", de: "Chỉ ra + tầng 1 + tầng 2 = 3 câu.",
          vd: "Biện pháp so sánh: “mặt trời” được so sánh với “quả cầu lửa”. Tác dụng: làm cho hình ảnh mặt trời trở nên cụ thể, sinh động, gợi hình gợi cảm. Người đọc hình dung được mặt trời to tròn, đỏ rực lúc hoàng hôn và cảm nhận được sự say mê của tác giả trước cảnh vật." },
      ],
      hop: { nhan: "Từ dùng cho tầng 2", chu: "Hình dung: to lớn / nhỏ bé / mềm mại / dữ dội / rực rỡ / trong trẻo… Tình cảm: yêu mến, trân trọng, ngợi ca, say mê, gắn bó, xót xa, nhớ thương. Chọn từ khớp với câu, mỗi bên một hai từ." },
    },
    {
      ten: "Luyện nhanh với văn bản đã học",
      doan: ["Trong “Đi lấy mật”, An tả ánh sáng buổi sáng trong rừng: “nhìn cái gì cũng có cảm giác như là nó bao qua một lớp thủy tinh”. Trong “Ngàn sao làm việc” có “ngôi sao Hôm như đuốc” và những vì sao dọc ngang “như tôm cua bơi lội”. Kim thử chọn một câu và viết tác dụng theo công thức hai tầng."],
    },
    {
      ten: "Ý nghĩa nằm ở vế B: vì sao tác giả chọn đúng hình ảnh ấy?",
      doan: ["Tầng 2 chỉ viết hay khi Kim hiểu vì sao tác giả chọn đúng hình ảnh B. Cách làm: tìm đặc điểm nổi bật nhất của B, xem đặc điểm ấy được chuyển sang A ra sao, rồi đoán người viết đang yêu, thương, kính trọng hay lo sợ A."],
      kn: [
        { ten: "“Công cha như núi Thái Sơn / Nghĩa mẹ như nước trong nguồn chảy ra” (ca dao)", de: "Núi Thái Sơn cao lớn, vững chãi, không đo hết. Nước nguồn chảy mãi không cạn. Chuyển sang: công cha lớn lao, vững vàng; tình mẹ dạt dào, bền bỉ, không bao giờ hết.",
          vd: "Ý nghĩa: ca ngợi công ơn cha mẹ vô cùng to lớn, nhắc con cái biết ơn, hiếu thảo." },
        { ten: "“Anh em như thể tay chân / Rách lành đùm bọc dở hay đỡ đần” (ca dao)", de: "Tay chân cùng một cơ thể, không tách rời, bên này đau thì bên kia cũng đau. Chuyển sang: anh em ruột thịt gắn bó không thể tách rời.",
          vd: "Ý nghĩa: khuyên anh em yêu thương, đùm bọc nhau lúc khó khăn. Dùng làm dẫn chứng cho tình anh em Mên và Mon rất hợp." },
        { ten: "Cùng vế A, đổi vế B (tự đặt)", de: "“Giọng bà ấm như nắng mùa đông” → giọng bà dịu dàng, cho cảm giác dễ chịu; người viết yêu thương bà. “Giọng bà to như cái loa phường” → giọng bà vang, khỏe; câu văn vui, hóm hỉnh.",
          vd: "Cùng tả giọng bà, đổi vế B là hình ảnh và tình cảm khác hẳn. Vì vậy tầng 2 phải bám vào vế B." },
        { ten: "“Bàn tay bố thô ráp như vỏ cây xoan” (tự đặt)", de: "Vỏ cây sần sùi, cứng, dãi nắng mưa. Chuyển sang: đôi tay bố chai sạn vì làm lụng vất vả.",
          vd: "Ý nghĩa: người viết thương bố, thấu hiểu sự vất vả bố chịu để nuôi con." },
        { ten: "“Lời mẹ dặn như ngọn đèn soi đường con đi” (tự đặt)", de: "Ngọn đèn soi sáng, dẫn lối trong bóng tối. Chuyển sang: lời mẹ giúp con biết đúng sai, không lạc lối.",
          vd: "Ý nghĩa: đề cao lời dạy bảo của mẹ, thể hiện lòng biết ơn mẹ." },
        { ten: "“Sân trường sau cơn mưa sạch như tấm gương vừa lau” (tự đặt)", de: "Tấm gương vừa lau sáng bóng, trong trẻo. Chuyển sang: sân trường sạch sẽ, sáng loáng, tươi mới.",
          vd: "Ý nghĩa: gợi cảm giác trong lành, dễ chịu; người viết yêu mến mái trường." },
      ],
      hop: { nhan: "Câu tầng 2 đầy đủ", chu: "Ví A với B (nêu đặc điểm nổi bật của B) giúp người đọc hình dung A … ; qua đó tác giả thể hiện tình cảm … với A." },
    },
  ],
  doiChieu: [
    ["Biện pháp tu từ", "Cách dùng chữ khéo để câu văn hay hơn, gợi hơn"],
    ["So sánh", "Ví A với B vì giống nhau ở một điểm"],
    ["Vế A / vế B", "Thứ đang nói tới / thứ đem ra ví"],
    ["Từ so sánh", "như, tựa, giống, là, hơn, chẳng bằng"],
    ["Gợi hình", "Làm người đọc hình dung ra hình ảnh"],
    ["Gợi cảm", "Làm người đọc có cảm xúc"],
  ],
  meo: "Thấy NHƯ, TỰA, GIỐNG là so sánh; thấy LÀ thì hỏi “có thật là không?”. Tác dụng viết HAI TẦNG: câu thuộc lòng (cụ thể, sinh động, gợi hình gợi cảm) + câu của mình (hình dung ra sao, tình cảm gì).",
  tuKiemTra: [
    { q: "Chỉ ra bốn bộ phận trong: “Tiếng suối trong như tiếng hát xa.”", a: "Vế A: tiếng suối. Phương diện: trong. Từ so sánh: như. Vế B: tiếng hát xa." },
    { q: "“Cô giáo là người mẹ thứ hai của em.” Có phải so sánh không?", a: "Có. Cô giáo không phải mẹ thật, tác giả ví cô với mẹ vì cô cũng yêu thương, dạy dỗ em. Từ so sánh là “là”." },
    { q: "“Bà em là giáo viên nghỉ hưu.” Có phải so sánh không?", a: "Không. Bà đúng là giáo viên thật, câu chỉ giới thiệu nghề của bà." },
    { q: "Nêu tác dụng của so sánh trong: “…nhìn cái gì cũng có cảm giác như là nó bao qua một lớp thủy tinh.” (viết hai tầng)", a: "Tầng 1: làm cho cảnh rừng buổi sáng hiện lên cụ thể, sinh động, gợi hình gợi cảm. Tầng 2: người đọc hình dung không khí rừng U Minh trong trẻo, tinh khiết, mọi vật như sáng lên lấp lánh; qua đó thấy được sự ngỡ ngàng, yêu mến của An trước vẻ đẹp thiên nhiên." },
    { q: "Đọc: “Những cánh buồm nâu trên biển như những cánh bướm khổng lồ.” Người đọc hình dung điều gì?", a: "Cánh buồm nhiều, nhẹ, dập dờn trên mặt biển, đẹp và sinh động như bướm đang bay. Tác giả yêu mến, say mê cảnh biển quê hương." },
    { q: "Bạn Hà trả lời tác dụng: “Làm câu văn hay hơn.” Thiếu gì?", a: "Thiếu cả hai tầng: chưa dùng đúng từ (cụ thể, sinh động, gợi hình gợi cảm) và chưa nói người đọc hình dung gì, tác giả bộc lộ tình cảm gì trong câu đó." },
    { q: "Câu ca dao “Anh em như thể tay chân…”: vì sao ví anh em với tay chân mà không ví với hai người bạn?", a: "Tay chân cùng một cơ thể, không thể tách rời, bên này đau thì bên kia cũng đau. Hình ảnh ấy cho thấy anh em là ruột thịt, gắn bó sâu sắc, nên phải đùm bọc, đỡ đần nhau." },
    { q: "Nêu tác dụng của so sánh trong “Công cha như núi Thái Sơn / Nghĩa mẹ như nước trong nguồn chảy ra” (hai tầng).", a: "Tầng 1: làm cho công ơn cha mẹ, vốn khó nói thành lời, trở nên cụ thể, gợi hình, gợi cảm. Tầng 2: núi Thái Sơn cao lớn, vững chãi cho thấy công cha lớn lao; nước nguồn chảy mãi cho thấy tình mẹ dạt dào, không bao giờ cạn. Qua đó câu ca dao ca ngợi công ơn cha mẹ và nhắc con cái phải biết ơn, hiếu thảo." },
    { q: "“Tóc bà bạc trắng như cước” và “Tóc bà trắng như mây” gợi cảm xúc khác nhau thế nào?", a: "Câu đầu nhấn vào tuổi già của bà, tóc đã bạc hết, gợi sự thương cảm. Câu sau gợi mái tóc nhẹ, mềm, hiền hậu và đẹp, thể hiện sự trìu mến, ngưỡng mộ." },
  ],
};

/* ===== Thứ Bảy 26/09 · Nhân hóa ===== */
window.KIM_GIANG["on-van-0926"] = {
  mon: "van",
  ngay: "2026-09-26",
  tieuDe: "Ôn Văn ngày 5 · Biện pháp tu từ nhân hóa",
  sgk: "Ôn lại kiến thức lớp 6 · dùng trong đề đọc hiểu",
  motCau: "Nhân hóa là cho con vật, cây cối, đồ vật, hiện tượng tự nhiên được gọi hoặc làm những việc chỉ người mới làm. Nhìn thấy “ông mặt trời”, “chị gió thì thầm”, “cây bàng đứng buồn” là có nhân hóa. Cách nêu tác dụng giống hôm qua: vẫn hai tầng, chỉ đổi câu học thuộc.",
  phan: [
    {
      ten: "Ba kiểu nhân hóa (nhớ để chỉ ra cho đúng)",
      kn: [
        { ten: "Gọi vật bằng từ gọi người", de: "ông, bà, chị, anh, cô, chú, bác… đặt trước tên vật.",
          vd: "ông mặt trời, chị gió, bác trống trường, cô mây, chú dế." },
        { ten: "Tả vật bằng từ tả người", de: "Vật có hành động, tính cách, cảm xúc của người.",
          vd: "Gió thì thầm với hàng cây. Con đường mệt mỏi nằm dài. Những vì sao vui làm việc." },
        { ten: "Trò chuyện, xưng hô với vật như với người", de: "Gọi vật là “mày”, “bạn”, hỏi han vật.",
          vd: "Trâu ơi ta bảo trâu này. Sông ơi, sao sông cứ chảy mãi thế?" },
      ],
      hop: { nhan: "Dễ nhầm với so sánh", chu: "“Con mèo lười như một ông cụ” là SO SÁNH (có chữ như, ví mèo với ông cụ). “Con mèo lười biếng nằm ngẫm nghĩ chuyện đời” là NHÂN HÓA (mèo làm việc của người: ngẫm nghĩ). Có chữ “như” thì nghĩ đến so sánh trước." },
    },
    {
      ten: "Tác dụng: công thức hai tầng của nhân hóa",
      buoc: [
        { so: 1, ten: "Tầng 1 · câu học thuộc", de: "Phép nhân hóa làm cho sự vật trở nên sinh động, gần gũi với con người, có hồn hơn.",
          vd: "Chép nguyên câu này vào bài." },
        { so: 2, ten: "Tầng 2 · nối với câu cụ thể", de: "Vật đó hiện lên giống người ở chỗ nào? Tác giả gửi tình cảm gì?",
          vd: "Với “Ngàn sao làm việc”: nhân hóa các vì sao thành những người lao động cần mẫn (sao Thần Nông cất vó, sao Đại Hùng tát nước) khiến bầu trời đêm trở nên rộn ràng như một cánh đồng đang mùa vụ, thể hiện cái nhìn tươi vui, yêu lao động của tác giả." },
        { so: 3, ten: "Ghép thành câu trả lời", de: "Chỉ ra kiểu nhân hóa + tầng 1 + tầng 2.",
          vd: "Biện pháp nhân hóa: các vì sao được tả như người đang làm việc (“cất vó”, “tát nước”). Tác dụng: làm bầu trời đêm trở nên sinh động, gần gũi, có hồn. Nhờ đó, người đọc thấy ngàn sao như một tập thể lao động vui tươi và cảm nhận được tình yêu cuộc sống lao động của nhà thơ." },
      ],
      hop: { nhan: "Chú ý", chu: "Từ “có hồn” chỉ dùng cho nhân hóa. Từ “gợi hình, gợi cảm” dùng cho so sánh và ẩn dụ. Dùng đúng từ, thầy cô biết ngay Kim phân biệt được." },
    },
    {
      ten: "Nhân hóa trong bài đã học",
      doan: ["“Ngàn sao làm việc” (Võ Quảng) là bài tràn ngập nhân hóa: sao Thần Nông tỏa rộng chiếc vó, sao Hôm soi cá chép, sao Đại Hùng tát nước, ngàn sao cùng làm việc rồi “nhọc nhằn” ngủ khi trời sáng. Nếu đề đọc hiểu lấy một khổ của bài này thì câu biện pháp tu từ gần như chắc chắn hỏi nhân hóa."],
    },
    {
      ten: "Vì sao tác giả cho vật làm người? Đọc ý nghĩa từng hình ảnh",
      doan: ["Khi vật được nói, được nghĩ, được vui buồn như người, tác giả thường gửi vào đó một tình cảm. Kim xem vật đang làm gì, đang vui hay đang buồn, để đoán tình cảm ấy."],
      kn: [
        { ten: "“Trâu ơi ta bảo trâu này / Trâu ra ngoài ruộng trâu cày với ta” (ca dao)", de: "Người nông dân gọi trâu, trò chuyện với trâu như với bạn, rủ trâu cùng ra đồng.",
          vd: "Ý nghĩa: trâu là người bạn thân thiết của nhà nông; câu ca dao thể hiện tình cảm yêu quý con trâu và niềm vui lao động." },
        { ten: "“Bầu ơi thương lấy bí cùng / Tuy rằng khác giống nhưng chung một giàn” (ca dao)", de: "Bầu, bí được gọi, được khuyên “thương” nhau như người. Đằng sau là con người: khác quê, khác họ nhưng cùng một đất nước.",
          vd: "Ý nghĩa: khuyên mọi người đoàn kết, yêu thương nhau. Câu này có cả nhân hóa (bầu bí biết thương) và ẩn dụ (bầu bí chỉ con người)." },
        { ten: "“Ông mặt trời vén mây, mỉm cười chào cả xóm.” (tự đặt)", de: "Mặt trời được gọi là ông, biết vén mây, biết cười, biết chào.",
          vd: "Ý nghĩa: không khí buổi sáng vui tươi, ấm áp, tràn sức sống; người viết yêu đời, yêu quê." },
        { ten: "“Chiếc cặp cũ nằm co ro trong góc tủ, nhớ những ngày được theo em đến lớp.” (tự đặt)", de: "Chiếc cặp biết co ro, biết nhớ.",
          vd: "Ý nghĩa: đồ vật như một người bạn cũ; câu văn gợi nỗi nhớ và sự gắn bó của em với kỉ niệm tuổi học trò." },
        { ten: "“Dòng sông mệt mỏi, oằn mình gánh rác thải của cả thành phố.” (tự đặt)", de: "Sông biết mệt, biết oằn mình gánh.",
          vd: "Ý nghĩa: người đọc thương dòng sông như thương một con người đang chịu khổ; lời nhắc nhẹ nhàng mà thấm thía về bảo vệ môi trường." },
      ],
      hop: { nhan: "Nhân hóa không chỉ để vui", chu: "Vật được nhân hóa đang vui thì câu văn tươi vui, yêu đời. Vật được nhân hóa đang buồn, mệt, đau thì câu văn gợi thương cảm, xót xa. Tầng 2 phải nói được tình cảm này." },
    },
  ],
  doiChieu: [
    ["Nhân hóa", "Cho vật được gọi, được tả hoặc được nói chuyện như người"],
    ["Gọi vật bằng từ gọi người", "ông, bà, chị, anh… + tên vật"],
    ["Tả vật bằng từ tả người", "Vật biết vui, buồn, thì thầm, chạy nhảy…"],
    ["Trò chuyện với vật", "Gọi “ơi”, xưng “mày”, “bạn” với vật"],
    ["Có hồn", "Vật như có tâm hồn, có tình cảm"],
  ],
  meo: "Nhân hóa = vật LÀM NGƯỜI. Ba kiểu nhớ theo ba chữ: GỌI (ông, chị), TẢ (thì thầm, buồn), NÓI CHUYỆN (trâu ơi). Tác dụng: sinh động, gần gũi, CÓ HỒN.",
  tuKiemTra: [
    { q: "Chỉ ra nhân hóa và kiểu nhân hóa: “Chị gió nhẹ nhàng vuốt tóc hàng dương.”", a: "Hai kiểu cùng lúc: gọi gió là “chị” (gọi vật bằng từ gọi người) và tả gió “vuốt tóc” (tả vật bằng từ tả người)." },
    { q: "“Trăng tròn như quả bóng.” Là so sánh hay nhân hóa?", a: "So sánh, vì có từ “như” và ví trăng với quả bóng. Trăng không làm việc gì của người." },
    { q: "“Trăng trốn sau đám mây rồi lại ló ra cười.” Là gì?", a: "Nhân hóa (tả vật bằng từ tả người): trăng biết trốn, biết cười." },
    { q: "Nêu tác dụng của nhân hóa trong: “Cây bàng già đứng lặng lẽ, trầm ngâm nhìn lũ trẻ chơi dưới sân.” (hai tầng)", a: "Tầng 1: làm cây bàng trở nên sinh động, gần gũi, có hồn. Tầng 2: cây bàng hiện lên như một ông lão hiền hậu đang lặng lẽ dõi theo lũ trẻ, gợi sự gắn bó thân thiết giữa cây với tuổi thơ và tình cảm yêu mến của tác giả với mái trường." },
    { q: "Trong “Ngàn sao làm việc”, các vì sao được nhân hóa thành ai?", a: "Thành những người lao động: sao Thần Nông cất vó, sao Đại Hùng tát nước, cả ngàn sao cùng làm việc suốt đêm rồi nghỉ khi trời sáng." },
    { q: "Viết một câu có nhân hóa về chiếc bút của Kim.", a: "Ví dụ: Chiếc bút nhỏ chăm chỉ chạy suốt tiết học rồi nằm nghỉ trong hộp. (bút biết chăm chỉ, chạy, nghỉ)" },
    { q: "Nêu tác dụng của nhân hóa trong: “Dòng sông mệt mỏi, oằn mình gánh rác thải của cả thành phố.” (hai tầng)", a: "Tầng 1: làm dòng sông trở nên sinh động, gần gũi, có hồn. Tầng 2: dòng sông hiện lên như một con người kiệt sức vì phải gánh quá nhiều rác, khiến người đọc xót xa, thương dòng sông; qua đó nhắc mọi người giữ gìn môi trường." },
    { q: "Trong câu ca dao “Trâu ơi ta bảo trâu này…”, vì sao người nông dân trò chuyện với trâu như với người?", a: "Vì trâu gắn bó với nhà nông như một người bạn cùng làm việc. Cách trò chuyện thân mật cho thấy tình cảm yêu quý, trân trọng con trâu." },
  ],
};

/* ===== Chủ nhật 27/09 · Ẩn dụ ===== */
window.KIM_GIANG["on-van-0927"] = {
  mon: "van",
  ngay: "2026-09-27",
  tieuDe: "Ôn Văn ngày 6 · Biện pháp tu từ ẩn dụ",
  sgk: "Ôn lại kiến thức lớp 6 (Ngữ văn 6 tập 1, Bài 3) · dùng trong đề đọc hiểu",
  motCau: "Ẩn dụ là so sánh mà giấu đi một vế. Thay vì nói “mẹ hiền như Bụt”, tác giả nói thẳng “Bụt của con” để chỉ mẹ. Người đọc phải tự đoán ra vế bị giấu. Đây là biện pháp khó nhất trong ba biện pháp, nên đề hay dùng để phân loại học sinh. Hôm nay tập cách tìm vế bị giấu.",
  phan: [
    {
      ten: "Ẩn dụ là so sánh ngầm: tìm vế bị giấu",
      doan: ["Cách nhận ra: có một từ ngữ nói về vật X, nhưng trong câu nó lại đang chỉ một vật Y khác giống X ở một điểm. Kim hỏi: từ này nghĩa đen là gì? Ở đây thật ra nó chỉ cái gì? Vì sao chỉ được?"],
      buoc: [
        { so: 1, ten: "Ví dụ 1", de: "“Ngày ngày mặt trời đi qua trên lăng / Thấy một mặt trời trong lăng rất đỏ.”",
          vd: "“Mặt trời” thứ hai nghĩa đen là mặt trời trên bầu trời, nhưng ở đây chỉ Bác Hồ, vì Bác cũng đem ánh sáng, sự sống cho dân tộc như mặt trời cho muôn loài. → Ẩn dụ." },
        { so: 2, ten: "Ví dụ 2", de: "“Thuyền về có nhớ bến chăng / Bến thì một dạ khăng khăng đợi thuyền.”",
          vd: "“Thuyền” chỉ người đi xa, “bến” chỉ người ở lại chờ đợi. Giống nhau: thuyền thì đi, bến thì đứng yên. → Ẩn dụ." },
        { so: 3, ten: "Ví dụ 3", de: "“Sao Thần Nông tỏa rộng / Một chiếc vó bằng vàng.”",
          vd: "Không có chữ “như”, nhưng chòm sao Thần Nông được gọi thẳng là “chiếc vó bằng vàng” vì hình dáng chòm sao giống cái vó cất cá. → Ẩn dụ (so sánh ngầm)." },
      ],
      hop: { nhan: "Phân biệt bằng một câu hỏi", chu: "So sánh: có cả A và B trong câu (mẹ hiền như Bụt). Ẩn dụ: chỉ còn B, A bị giấu (Bụt của con). Nhân hóa: vật làm việc của người. Gặp câu khó, Kim hỏi “vế A ở đâu?”: có A → so sánh; không có A mà B đang chỉ một thứ khác → ẩn dụ." },
    },
    {
      ten: "Bốn kiểu ẩn dụ (biết để gọi tên khi đề hỏi)",
      kn: [
        { ten: "Ẩn dụ hình thức", de: "Giống nhau về hình dáng.", vd: "“chiếc vó bằng vàng” chỉ chòm sao Thần Nông; “thắp lên lửa hồng” chỉ hoa râm bụt đỏ." },
        { ten: "Ẩn dụ cách thức", de: "Giống nhau về cách làm.", vd: "“Ăn quả nhớ kẻ trồng cây”: trồng cây là cách tạo ra thành quả, chỉ người đi trước làm nên điều tốt đẹp." },
        { ten: "Ẩn dụ phẩm chất", de: "Giống nhau về tính chất, đặc điểm.", vd: "“mặt trời trong lăng” chỉ Bác Hồ; “người cha mái tóc bạc” chỉ Bác trong bài Đêm nay Bác không ngủ." },
        { ten: "Ẩn dụ chuyển đổi cảm giác", de: "Dùng từ của giác quan này để tả giác quan khác.", vd: "“giọng nói ngọt ngào” (vị giác tả thính giác); “nắng giòn tan” (vị giác tả thị giác); “tiếng cười sáng cả căn phòng”." },
      ],
      hop: { nhan: "Đề lớp 7 thường chỉ hỏi", chu: "“Chỉ ra biện pháp tu từ và nêu tác dụng”. Kim chỉ cần nói “ẩn dụ” và giải thích B chỉ A. Gọi đúng kiểu là điểm cộng, không bắt buộc. Nếu không chắc kiểu thì đừng ghi, ghi sai còn bị trừ." },
    },
    {
      ten: "Tác dụng: hai tầng cho ẩn dụ",
      buoc: [
        { so: 1, ten: "Tầng 1 · câu học thuộc", de: "Phép ẩn dụ làm cho cách diễn đạt trở nên hàm súc, gợi hình, gợi cảm, giàu sức gợi.",
          vd: "Chép nguyên câu này vào bài." },
        { so: 2, ten: "Tầng 2 · giải nghĩa và tình cảm", de: "Nói rõ B chỉ A, giống nhau ở chỗ nào, tác giả bày tỏ tình cảm gì.",
          vd: "“Mặt trời trong lăng” chỉ Bác Hồ: Bác đem lại ánh sáng độc lập, tự do cho dân tộc như mặt trời đem sự sống cho muôn loài. Qua đó tác giả bày tỏ lòng thành kính, biết ơn Bác." },
      ],
    },
    {
      ten: "Ẩn dụ trong tục ngữ, ca dao và lời nói hằng ngày",
      doan: ["Ẩn dụ luôn phải giải nghĩa: B chỉ A vì cùng một đặc điểm. Chưa giải nghĩa thì chưa có điểm tầng 2. Dưới đây là những câu Kim nghe quen mà chưa để ý là ẩn dụ."],
      kn: [
        { ten: "“Uống nước nhớ nguồn” (tục ngữ)", de: "“Nước” chỉ những điều tốt đẹp mình được hưởng; “nguồn” chỉ người làm ra điều đó: ông bà, cha mẹ, thầy cô, người đi trước.",
          vd: "Ý nghĩa: nhắc lòng biết ơn. Hình ảnh nguồn nước rất hợp: không có nguồn thì không có dòng sông." },
        { ten: "“Gần mực thì đen, gần đèn thì sáng” (tục ngữ)", de: "“Mực” chỉ người xấu, môi trường xấu; “đèn” chỉ người tốt, môi trường tốt.",
          vd: "Ý nghĩa: khuyên chọn bạn mà chơi, vì những người quanh mình ảnh hưởng tới mình." },
        { ten: "“Mỗi sáng, mẹ lại tiễn ánh nắng nhỏ của mẹ đến trường.” (tự đặt)", de: "“Ánh nắng nhỏ” chỉ đứa con. Giống nhau: ấm áp, đem lại niềm vui và sức sống.",
          vd: "Ý nghĩa: con là niềm vui, niềm hạnh phúc của mẹ; câu văn thấm tình mẹ." },
        { ten: "“Bữa cơm rộn lên tiếng cười giòn tan của bé Na.” (tự đặt)", de: "“Giòn tan” vốn tả món ăn, ở đây tả tiếng cười. Ẩn dụ chuyển đổi cảm giác.",
          vd: "Ý nghĩa: tiếng cười vang, trong và vui, gợi không khí gia đình ấm cúng." },
      ],
      hop: { nhan: "Mẹo phân biệt với câu có chữ “là”", chu: "“Con là ánh nắng của mẹ” có cả A (con) và B (ánh nắng) nên là SO SÁNH. “Ánh nắng nhỏ của mẹ đến trường” chỉ còn B, A bị giấu nên là ẨN DỤ." },
    },
  ],
  doiChieu: [
    ["Ẩn dụ", "So sánh ngầm: chỉ nói vế B, giấu vế A"],
    ["Nghĩa đen", "Nghĩa thường ngày của từ"],
    ["Nghĩa ẩn dụ", "Nghĩa mà từ đó đang chỉ trong câu"],
    ["Hàm súc", "Ít chữ mà nhiều ý"],
    ["Ẩn dụ chuyển đổi cảm giác", "Dùng từ của giác quan này tả giác quan khác (giọng nói ngọt)"],
  ],
  meo: "Ẩn dụ = so sánh GIẤU VẾ A. Gặp từ lạ chỗ, hỏi: nghĩa đen là gì, ở đây thật ra chỉ gì, giống ở chỗ nào. Tác dụng: HÀM SÚC, gợi hình gợi cảm, rồi giải nghĩa B chỉ A.",
  tuKiemTra: [
    { q: "“Người cha mái tóc bạc / Đốt lửa cho anh nằm.” Từ nào là ẩn dụ, chỉ ai?", a: "“Người cha” chỉ Bác Hồ, vì Bác chăm lo cho các anh bộ đội như cha lo cho con. Ẩn dụ phẩm chất." },
    { q: "“Mẹ hiền như Bụt” và “Bụt của con ơi” khác nhau ở chỗ nào?", a: "Câu đầu là so sánh: có cả mẹ (A), như, Bụt (B). Câu sau là ẩn dụ: chỉ còn Bụt (B), người đọc tự hiểu Bụt chỉ mẹ." },
    { q: "“Giọng cô giáo ấm áp làm cả lớp yên lặng.” Ẩn dụ kiểu gì?", a: "Ẩn dụ chuyển đổi cảm giác: “ấm áp” là cảm giác của da (xúc giác) dùng để tả giọng nói (thính giác)." },
    { q: "“Ăn quả nhớ kẻ trồng cây” khuyên điều gì? Ẩn dụ ở đâu?", a: "“Quả” chỉ thành quả ta được hưởng, “kẻ trồng cây” chỉ người đã làm ra thành quả đó. Câu khuyên phải biết ơn người đi trước. Ẩn dụ cách thức." },
    { q: "Nêu tác dụng của ẩn dụ trong “Thuyền về có nhớ bến chăng / Bến thì một dạ khăng khăng đợi thuyền” (hai tầng).", a: "Tầng 1: cách nói hàm súc, gợi hình gợi cảm. Tầng 2: “thuyền” chỉ người đi xa, “bến” chỉ người ở lại; qua hình ảnh bến đứng yên đợi thuyền, câu ca dao diễn tả tấm lòng thủy chung, son sắt của người ở lại." },
    { q: "“Sao Thần Nông tỏa rộng / Một chiếc vó bằng vàng”: vì sao là ẩn dụ chứ không phải nhân hóa?", a: "Vì “chiếc vó bằng vàng” là hình ảnh dùng để chỉ hình dáng chòm sao (so sánh ngầm), không phải chòm sao đang làm việc của người. Còn “tỏa rộng” chiếc vó thì lại là nhân hóa: cả hai biện pháp cùng có trong hai câu thơ." },
    { q: "“Gần mực thì đen, gần đèn thì sáng”: “mực” và “đèn” chỉ gì? Câu tục ngữ khuyên điều gì?", a: "“Mực” chỉ người xấu, môi trường xấu; “đèn” chỉ người tốt, môi trường tốt. Câu tục ngữ khuyên chọn bạn tốt mà chơi, vì môi trường sống ảnh hưởng đến con người." },
    { q: "“Con là ánh nắng của mẹ” là so sánh hay ẩn dụ? Còn “Mẹ tiễn ánh nắng nhỏ của mẹ đến trường”?", a: "Câu đầu là so sánh vì có cả A (con) và B (ánh nắng). Câu sau là ẩn dụ vì chỉ còn B, người đọc tự hiểu “ánh nắng nhỏ” là đứa con." },
  ],
};

/* ===== Thứ Hai 28/09 · Tổng hợp tiếng Việt ===== */
window.KIM_GIANG["on-van-0928"] = {
  mon: "van",
  ngay: "2026-09-28",
  tieuDe: "Ôn Văn ngày 7 · Tổng hợp tiếng Việt: ba biện pháp tu từ và mở rộng câu",
  sgk: "Gộp bài ngày 4, 5, 6 và bài Mở rộng câu (20/09)",
  motCau: "Phần Tiếng Việt trong đề thường là hai câu, mỗi câu 1 điểm: một câu về biện pháp tu từ, một câu về trạng ngữ hoặc mở rộng thành phần câu. Hôm nay không học gì mới, chỉ xếp mọi thứ vào một bảng để Kim làm nhanh và không lẫn.",
  phan: [
    {
      ten: "Bảng phân biệt ba biện pháp tu từ",
      kn: [
        { ten: "So sánh", de: "Dấu hiệu: có từ so sánh (như, tựa, là, hơn); có cả A và B. Tác dụng thuộc lòng: cụ thể, sinh động, gợi hình gợi cảm.",
          vd: "Mặt trời đỏ như quả cầu lửa." },
        { ten: "Nhân hóa", de: "Dấu hiệu: vật được gọi (ông, chị), làm việc hoặc có cảm xúc của người, được nói chuyện cùng. Tác dụng thuộc lòng: sinh động, gần gũi, có hồn.",
          vd: "Chị gió thì thầm với hàng cây." },
        { ten: "Ẩn dụ", de: "Dấu hiệu: một từ đứng “lạ chỗ”, không có từ so sánh, chỉ còn vế B. Tác dụng thuộc lòng: hàm súc, gợi hình gợi cảm, giàu sức gợi.",
          vd: "Mặt trời trong lăng rất đỏ." },
      ],
      hop: { nhan: "Thứ tự kiểm tra khi gặp câu lạ", chu: "Bước 1: có “như / là / tựa” không? Có → so sánh. Bước 2: vật có đang làm việc của người không? Có → nhân hóa. Bước 3: có từ nào nghĩa đen không hợp, đang chỉ thứ khác không? Có → ẩn dụ. Một câu có thể có hai biện pháp, khi đó nêu cả hai." },
    },
    {
      ten: "Mẫu câu trả lời chung cho câu biện pháp tu từ (1 điểm)",
      buoc: [
        { so: 1, ten: "Gọi tên và chỉ ra", de: "Biện pháp tu từ …: (trích chữ trong ngoặc kép).", vd: "Biện pháp nhân hóa: “chị gió thì thầm”." },
        { so: 2, ten: "Tác dụng tầng 1", de: "Câu học thuộc tương ứng.", vd: "Làm cho hình ảnh gió trở nên sinh động, gần gũi, có hồn." },
        { so: 3, ten: "Tác dụng tầng 2", de: "Hình dung + tình cảm, nối với câu đang hỏi.", vd: "Gió như một người bạn dịu dàng đang trò chuyện với cây, gợi khung cảnh yên bình và tình yêu thiên nhiên của tác giả." },
      ],
      hop: { nhan: "Biểu điểm thường thấy", chu: "Gọi đúng tên và chỉ ra đúng chữ: 0,5 điểm. Nêu tác dụng đủ hai tầng: 0,5 điểm. Chỉ viết “làm câu văn hay hơn” là mất 0,5 điểm." },
    },
    {
      ten: "Câu về trạng ngữ và mở rộng câu: ba dạng đề",
      buoc: [
        { so: 1, ten: "Tìm trạng ngữ và nêu ý nghĩa", de: "Trạng ngữ trả lời khi nào / ở đâu / vì sao / để làm gì. Ghi cả cụm, rồi ghi ý nghĩa.",
          vd: "“Suốt từ chiều hôm qua, nước đã dâng lên nhanh hơn.” → Trạng ngữ “Suốt từ chiều hôm qua” chỉ thời gian." },
        { so: 2, ten: "Nêu tác dụng của việc mở rộng trạng ngữ bằng cụm từ", de: "Mẫu: giúp câu cung cấp thông tin cụ thể hơn về thời gian / nơi chốn…, sự việc được miêu tả rõ ràng, sinh động hơn.",
          vd: "So với “Hôm qua, nước dâng lên”, cụm “Suốt từ chiều hôm qua” cho biết nước dâng liên tục, từ rất sớm, gợi sự lo lắng." },
        { so: 3, ten: "Mở rộng thành phần chính bằng cụm từ", de: "Đề cho câu ngắn, yêu cầu mở rộng chủ ngữ hoặc vị ngữ, rồi so sánh hai câu.",
          vd: "“Chim hót.” → “Những chú chim sâu nhỏ xíu / đang hót líu lo trên cành bưởi.” Câu mở rộng cho biết loài chim, số lượng, cách hót và nơi hót, nên rõ và sinh động hơn." },
      ],
      hop: { nhan: "Cách trình bày khi đề bảo gạch chân", chu: "Chép lại câu, gạch dưới trọn cụm, ghi chú ngắn bên cạnh: (TN chỉ thời gian) hoặc (CN được mở rộng). Gạch thiếu chữ là bị coi như sai." },
    },
  ],
  doiChieu: [
    ["So sánh", "Có A, có B, có từ như"],
    ["Nhân hóa", "Vật làm người"],
    ["Ẩn dụ", "B chỉ A, A bị giấu"],
    ["Trạng ngữ", "Phần thêm chỉ thời gian, nơi chốn, nguyên nhân, mục đích"],
    ["Mở rộng bằng cụm từ", "Thay một từ bằng một cụm để rõ hơn"],
    ["Cụm danh từ / cụm động từ / cụm tính từ", "Cụm có từ chính là danh từ / động từ / tính từ"],
  ],
  meo: "Ba câu thuộc lòng, mỗi biện pháp một câu: so sánh CỤ THỂ SINH ĐỘNG, nhân hóa GẦN GŨI CÓ HỒN, ẩn dụ HÀM SÚC. Trả lời luôn theo ba nhịp: gọi tên và chỉ ra, câu thuộc lòng, câu của mình.",
  tuKiemTra: [
    { q: "“Bờ tre xanh rì rào kể chuyện với dòng sông.” Biện pháp gì? Trả lời đủ ba nhịp.", a: "Nhân hóa: bờ tre “kể chuyện” với dòng sông. Tác dụng: làm bờ tre, dòng sông trở nên sinh động, gần gũi, có hồn. Cảnh làng quê hiện lên thân thiết như những người bạn đang trò chuyện, cho thấy tình yêu quê hương của tác giả." },
    { q: "“Quê hương là chùm khế ngọt.” Biện pháp gì? Vì sao?", a: "So sánh (từ so sánh “là”, có cả A là quê hương và B là chùm khế ngọt). Quê hương không phải chùm khế thật, tác giả ví để nói quê hương ngọt ngào, thân thuộc như tuổi thơ." },
    { q: "“Thuyền ta lái gió với buồm trăng.” Có ẩn dụ không?", a: "Có. “Buồm trăng” là ẩn dụ: cánh buồm căng dưới ánh trăng như được làm bằng trăng, gợi vẻ đẹp lãng mạn của thuyền đánh cá ban đêm." },
    { q: "Tìm trạng ngữ và nêu ý nghĩa: “Vì trời mưa to, buổi lao động của lớp em phải hoãn lại.”", a: "Trạng ngữ “Vì trời mưa to” chỉ nguyên nhân." },
    { q: "Mở rộng chủ ngữ và vị ngữ: “Mèo ngủ.”", a: "Ví dụ: Chú mèo mướp lười biếng của bà / đang ngủ say trên chiếc ghế mây ngoài hiên." },
    { q: "Nêu tác dụng của việc mở rộng trạng ngữ: “Sáng, em đi học” thành “Sáng sớm mùa đông giá rét, em đi học”.", a: "Trạng ngữ được mở rộng cho biết cụ thể hơn về thời gian và thời tiết, làm sự việc đi học hiện lên rõ ràng, sinh động hơn, gợi sự vất vả của người đi học." },
    { q: "Câu “Cánh đồng lúa chín vàng như một tấm thảm khổng lồ trải dài đến chân trời” có mấy biện pháp tu từ?", a: "Một: so sánh (cánh đồng như tấm thảm). Không có nhân hóa vì cánh đồng không làm việc của người." },
  ],
};

/* ===== Thứ Ba 29/09 · Đề đọc hiểu trọn vẹn số 1 ===== */
window.KIM_GIANG["on-van-0929"] = {
  mon: "van",
  ngay: "2026-09-29",
  tieuDe: "Ôn Văn ngày 8 · Làm thử một đề đọc hiểu trọn vẹn (5 điểm, 25 phút)",
  sgk: "Đề tự soạn theo cấu trúc đề kiểm tra · văn bản ngoài SGK",
  motCau: "Hôm nay không học lí thuyết. Kim bấm giờ 25 phút, đọc văn bản dưới đây và viết câu trả lời ra vở cho đủ 6 câu, xong mới mở đáp án từng câu để tự chấm. Mục tiêu không phải đúng hết, mà là biết câu nào mình trả lời thiếu ý.",
  phan: [
    {
      ten: "Văn bản đọc hiểu",
      doan: [
        "CON DIỀU CỦA NGOẠI",
        "Suốt cả tuần trước ngày hội làng, ông ngoại ngồi ở hiên nhà vót nan tre. Những thanh tre mảnh như que tăm được ông uốn cong rồi buộc lại bằng sợi chỉ đỏ. Bé Hạnh ngồi bên cạnh, tay chống cằm, mắt không rời đôi bàn tay chai sần của ông.",
        "– Diều này ông làm cho ai thế? – Hạnh hỏi.",
        "– Cho một người sắp phải đi xa. – Ông cười, mắt vẫn nhìn vào thanh tre.",
        "Hạnh ngẩn ra. Con bé biết tháng sau mình theo bố mẹ lên thành phố học. Nó không nói gì, chỉ cúi xuống nhặt mấy sợi tre vụn cho vào rổ.",
        "Chiều hôm hội, gió từ ngoài đê thổi vào lồng lộng. Con diều giấy màu đỏ chao đi một vòng rồi vút lên, cái đuôi dài phất phới như đang vẫy tay chào cả cánh đồng. Hạnh cầm cuộn dây chạy mãi trên bờ cỏ, tiếng cười rơi theo từng bước chân. Ông ngoại đứng ở gốc gạo, tay che nắng nhìn theo, và con bé không thấy ông đã lặng lẽ lau mắt.",
        "Tối ấy, ông cuộn con diều lại thật cẩn thận rồi đưa cho Hạnh:",
        "– Lên trên ấy, lúc nào nhớ quê thì thả nó lên. Gió ở đâu cũng là gió cả.",
        "(Truyện ngắn tự sáng tác, dùng để luyện tập)",
      ],
    },
    {
      ten: "Câu hỏi (làm ra vở, bấm giờ 25 phút)",
      doan: [
        "Câu 1 (0,5 điểm). Văn bản được kể theo ngôi thứ mấy? Dựa vào đâu em biết?",
        "Câu 2 (0,5 điểm). Nêu đề tài của văn bản.",
        "Câu 3 (1 điểm). Chỉ ra và nêu tác dụng của một biện pháp tu từ trong câu: “Con diều giấy màu đỏ chao đi một vòng rồi vút lên, cái đuôi dài phất phới như đang vẫy tay chào cả cánh đồng.”",
        "Câu 4 (1 điểm). Tìm trạng ngữ trong câu “Suốt cả tuần trước ngày hội làng, ông ngoại ngồi ở hiên nhà vót nan tre.” Trạng ngữ đó được mở rộng bằng cụm từ có tác dụng gì?",
        "Câu 5 (1 điểm). Chi tiết ông ngoại “lặng lẽ lau mắt” khi nhìn cháu thả diều cho em hiểu gì về nhân vật người ông?",
        "Câu 6 (1 điểm). Câu nói của ông “Gió ở đâu cũng là gió cả” gợi cho em bài học gì? Trình bày bằng 2–3 câu.",
      ],
      hop: { nhan: "Làm xong mới mở đáp án", chu: "Đáp án từng câu nằm ở phần Kim tự kiểm tra bên dưới. Chấm xong, ghi điểm vào vở để mẹ xem." },
    },
  ],
  doiChieu: [
    ["Câu 0,5 điểm", "Trả lời một câu, đúng là đủ"],
    ["Câu 1 điểm về biện pháp tu từ", "Gọi tên + chỉ ra + tác dụng hai tầng"],
    ["Câu 1 điểm về nhân vật, bài học", "Hai đến ba câu, có dẫn chi tiết"],
  ],
  meo: "Phân bổ thời gian cho đọc hiểu: đọc văn bản 4 phút, hai câu nhận biết 3 phút, hai câu tiếng Việt 8 phút, hai câu cuối 10 phút. Câu nào bí thì bỏ qua làm câu sau, cuối giờ quay lại.",
  tuKiemTra: [
    { q: "Đáp án câu 1", a: "Ngôi thứ ba. Người kể giấu mặt, gọi nhân vật là “ông ngoại”, “bé Hạnh”, “con bé”. (Lời thoại có “ông”, “cháu” không tính.)" },
    { q: "Đáp án câu 2", a: "Đề tài: tình cảm gia đình (tình ông cháu) / tình yêu quê hương qua kỉ niệm tuổi thơ. Chỉ cần nêu một trong hai." },
    { q: "Đáp án câu 3", a: "Có hai biện pháp, chọn một. So sánh: đuôi diều “như đang vẫy tay chào cả cánh đồng”; tác dụng: làm hình ảnh con diều hiện lên cụ thể, sinh động, gợi hình gợi cảm; người đọc hình dung cái đuôi diều bay lượn vui tươi như một lời chào thân thiết, gợi niềm vui của Hạnh và sự gắn bó với quê hương. Nhân hóa: con diều “vẫy tay chào”; tác dụng: làm con diều trở nên sinh động, gần gũi, có hồn, như một người bạn của Hạnh đang chào tạm biệt cánh đồng." },
    { q: "Đáp án câu 4", a: "Trạng ngữ: “Suốt cả tuần trước ngày hội làng” (chỉ thời gian). Việc mở rộng bằng cụm từ giúp câu cho biết cụ thể hơn thời gian ông làm diều: không phải một lúc mà suốt cả tuần, làm nổi bật sự kiên nhẫn và tình thương của ông dành cho cháu." },
    { q: "Đáp án câu 5", a: "Ông ngoại là người rất mực yêu thương cháu và giàu tình cảm. Ông vui khi thấy cháu cười, nhưng lại lặng lẽ lau nước mắt vì biết cháu sắp đi xa. Ông giấu nỗi buồn để cháu được trọn vẹn niềm vui trong ngày hội. Cần có đủ hai ý: thương cháu và giấu nỗi buồn." },
    { q: "Đáp án câu 6", a: "Ví dụ: Câu nói của ông nhắc em rằng dù đi đâu, quê hương và người thân vẫn ở trong lòng mình, chỉ cần mình nhớ đến thì họ luôn gần. Em cũng học được cách người lớn yêu thương con cháu: không giữ lại mà dặn dò để cháu vững vàng nơi xa. Từ đó em thấy cần trân trọng những ngày còn được ở bên ông bà." },
    { q: "Tự chấm: Kim được bao nhiêu điểm? Câu nào thiếu ý?", a: "Ghi lại số điểm vào vở. Câu nào thiếu ý thì đọc lại bài ôn của ngày tương ứng: ngôi kể (22/09), đề tài và chi tiết (23/09), nhân vật và bài học (24/09), biện pháp tu từ (25–28/09)." },
  ],
};

/* ===== Thứ Tư 30/09 · Viết đoạn văn: ý nghĩa, lợi ích, vai trò ===== */
window.KIM_GIANG["on-van-0930"] = {
  mon: "van",
  ngay: "2026-09-30",
  tieuDe: "Ôn Văn ngày 9 · Viết đoạn văn 10–12 câu: ba kiểu đề ý nghĩa, lợi ích, vai trò",
  sgk: "Dựa trên khung sáu bước đã học ngày 20/09 · Ngữ văn 7 tập 1, phần Viết Bài 1 và Bài 2",
  motCau: "Đề phần Viết (5 điểm) yêu cầu đoạn văn khoảng 10–12 câu trình bày ý kiến về một vấn đề đời sống. Đề có thể hỏi “ý nghĩa”, “lợi ích” hay “vai trò” của một điều gì đó. Ba chữ này gần giống nhau, khung viết dùng chung, chỉ khác ở cách đặt câu trong phần thân. Hôm nay ôn lại khung và học cách chuyển đổi giữa ba chữ.",
  phan: [
    {
      ten: "Nhắc lại khung sáu bước, đếm theo dãy 1–1–3–1–1–2",
      doan: ["Kim đã học khung này ngày 20/09. Ghi lại cho nhớ: câu mở nêu vấn đề (1) → giải thích vấn đề là gì (1) → phần chính: 3 ý, mỗi ý một câu có vế vì/nhờ đó (3) → dẫn chứng (1) → phê phán mặt trái (1) → bài học và câu kết (2). Cộng lại 9–10 câu, thêm một câu dẫn chứng thứ hai hoặc một câu giải thích nữa là đủ 10–12 câu."],
      hop: { nhan: "Vì sao dãy số quan trọng", chu: "Thầy cô chấm theo ý: có giải thích không, có đủ 2–3 lí lẽ không, có dẫn chứng không, có phản đề không, có bài học không. Viết dài mà thiếu một mục vẫn mất điểm. Dãy số là cách kiểm tra nhanh trước khi nộp." },
    },
    {
      ten: "Ba chữ trong đề khác nhau ở đâu",
      kn: [
        { ten: "Ý nghĩa của X", de: "Hỏi X tốt ở chỗ nào, làm cho cuộc sống đẹp hơn ra sao. Câu thân bài mở bằng: “X giúp / X khiến / X làm cho…”.",
          vd: "Ý nghĩa của lòng biết ơn: giúp ta sống tình nghĩa; khiến người giúp ta thấy vui; làm xã hội gắn bó." },
        { ten: "Lợi ích của X", de: "Hỏi X đem lại điều gì có ích, cụ thể, đo đếm được. Câu thân bài mở bằng: “Nhờ X, ta có / được…”. Thường dùng cho việc làm: đọc sách, tập thể dục, tự học.",
          vd: "Lợi ích của việc tập thể dục: nhờ tập đều, cơ thể khỏe mạnh; đầu óc tỉnh táo học tốt hơn; có thêm bạn cùng chơi." },
        { ten: "Vai trò của X", de: "Hỏi X quan trọng thế nào, nếu thiếu X thì sao. Câu thân bài mở bằng: “X là nơi / là nguồn / là chỗ dựa…”, và có thể thêm một câu “Nếu không có X…”. Thường dùng cho gia đình, thầy cô, tình bạn, quê hương.",
          vd: "Vai trò của gia đình: là nơi ta được sinh ra và yêu thương; là chỗ dựa khi vấp ngã; là nơi dạy ta những bài học đầu tiên. Nếu thiếu gia đình, con người dễ cô đơn, lạc lối." },
      ],
      hop: { nhan: "Mẹo đổi đề", chu: "Gặp đề “vai trò”, Kim viết y như “ý nghĩa” nhưng thêm một câu “Nếu không có X thì…” vào cuối phần thân. Gặp đề “lợi ích”, các ý phải cụ thể hơn, nói được ta ĐƯỢC GÌ." },
    },
    {
      ten: "Lập dàn ý mẫu: Lợi ích của việc tập thể dục thể thao",
      buoc: [
        { so: 1, ten: "Mở đoạn", de: "Nêu vấn đề.", vd: "Tập thể dục thể thao là một thói quen mang lại rất nhiều lợi ích cho mỗi người." },
        { so: 2, ten: "Giải thích", de: "X là gì.", vd: "Tập thể dục thể thao là việc vận động cơ thể đều đặn qua các hoạt động như chạy bộ, đá bóng, bơi lội hay đơn giản là đi bộ mỗi ngày." },
        { so: 3, ten: "Ba lợi ích", de: "Mỗi ý một câu, có vế nhờ đó.", vd: "Trước hết, nhờ vận động, cơ thể trở nên khỏe mạnh, dẻo dai và ít ốm vặt. Không chỉ vậy, sau mỗi buổi tập, đầu óc thư giãn, tỉnh táo nên học tập hiệu quả hơn. Hơn nữa, khi cùng chơi thể thao, ta có thêm bạn bè và học được tinh thần đồng đội." },
        { so: 4, ten: "Dẫn chứng", de: "Một ví dụ thật.", vd: "Ở lớp em, các bạn tham gia câu lạc bộ bóng rổ luôn vui vẻ, nhanh nhẹn và rất ít khi nghỉ học vì ốm." },
        { so: 5, ten: "Mặt trái", de: "Phê phán.", vd: "Thế nhưng, vẫn có nhiều bạn dành cả buổi chiều cho điện thoại mà lười vận động, khiến sức khỏe ngày càng yếu đi." },
        { so: 6, ten: "Bài học và kết", de: "Việc cụ thể + khẳng định.", vd: "Là học sinh, em sẽ dành ba mươi phút mỗi chiều để đạp xe hoặc nhảy dây. Chăm tập thể dục chính là cách đơn giản nhất để có một cuộc sống khỏe mạnh và vui tươi." },
      ],
      hop: { nhan: "Đếm thử", chu: "Dàn ý trên có 1+1+3+1+1+2 = 9 câu. Thêm một câu dẫn chứng nữa (chẳng hạn về một vận động viên Kim thích) là 10 câu. Muốn 12 câu thì thêm một câu giải thích vì sao ở ý thứ hai." },
    },
  ],
  doiChieu: [
    ["Ý nghĩa", "X tốt ở chỗ nào"],
    ["Lợi ích", "X đem lại cái gì có ích, cụ thể"],
    ["Vai trò", "X quan trọng thế nào, thiếu X thì sao"],
    ["Trình bày ý kiến", "Nêu điều mình nghĩ và giải thích vì sao"],
    ["Lí lẽ", "Câu vì sao"],
    ["Dẫn chứng", "Ví dụ thật"],
  ],
  meo: "Ý NGHĨA: X giúp gì. LỢI ÍCH: nhờ X ta được gì. VAI TRÒ: X là chỗ dựa, thiếu X thì sao. Khung vẫn là 1–1–3–1–1–2.",
  tuKiemTra: [
    { q: "Đề “Trình bày suy nghĩ về vai trò của tình bạn”: Kim thêm câu gì vào phần thân so với đề “ý nghĩa”?", a: "Một câu “Nếu không có bạn bè, cuộc sống sẽ cô đơn, buồn tẻ, khó khăn cũng khó vượt qua hơn.” đặt sau ba ý chính." },
    { q: "Viết câu mở đoạn cho đề “lợi ích của việc đọc sách”.", a: "Ví dụ: Đọc sách là một thói quen tốt mang lại nhiều lợi ích cho mỗi người." },
    { q: "Viết câu giải thích cho đề “vai trò của gia đình”.", a: "Ví dụ: Gia đình là nơi có ông bà, cha mẹ, anh chị em cùng chung sống, yêu thương và chăm sóc lẫn nhau." },
    { q: "Nêu ba lợi ích của việc tự học ở nhà, mỗi lợi ích một câu có vế “nhờ đó”.", a: "Ví dụ: Trước hết, nhờ tự học, em hiểu bài sâu hơn vì được tự mình suy nghĩ. Không chỉ vậy, tự học giúp em chủ động thời gian, nhờ đó không phải phụ thuộc vào lớp học thêm. Hơn nữa, thói quen tự học rèn cho em tính kiên trì, nhờ đó sau này làm việc gì cũng bền bỉ." },
    { q: "Đoạn văn của bạn Minh có mở, giải thích, ba ý, dẫn chứng, bài học nhưng không có câu “Thế nhưng”. Minh thiếu gì?", a: "Thiếu phần phê phán mặt trái (phản đề). Đây là mục thầy cô hay chấm riêng 0,5 điểm." },
    { q: "Câu bài học nào tốt hơn: (a) “Em sẽ chăm tập thể dục.” (b) “Em sẽ dành ba mươi phút mỗi chiều để đạp xe quanh khu nhà.”", a: "(b), vì nói được việc cụ thể, thời gian cụ thể. Câu (a) chung chung." },
  ],
};

/* ===== Thứ Năm 01/10 · Tự viết một đoạn văn hoàn chỉnh ===== */
window.KIM_GIANG["on-van-1001"] = {
  mon: "van",
  ngay: "2026-10-01",
  tieuDe: "Ôn Văn ngày 10 · Tự viết đoạn văn: Vai trò của gia đình đối với mỗi người",
  sgk: "Luyện viết có bấm giờ · 25 phút",
  motCau: "Hôm nay Kim viết thật, vào vở, bấm giờ 25 phút, không nhìn dàn ý mẫu. Đề: “Viết đoạn văn khoảng 10–12 câu trình bày suy nghĩ của em về vai trò của gia đình đối với mỗi người.” Viết xong mới mở phần tự kiểm tra để chấm theo bảng và so với đoạn mẫu.",
  phan: [
    {
      ten: "Trước khi viết (3 phút)",
      buoc: [
        { so: 1, ten: "Gạch chân đề", de: "Hình thức, vấn đề, yêu cầu.", vd: "Đoạn văn 10–12 câu · gia đình · vai trò (nhớ thêm câu “nếu không có…”)." },
        { so: 2, ten: "Ghi nháp ba ý", de: "Chỉ ghi từ khóa, không viết câu.", vd: "nơi sinh ra, được yêu thương · chỗ dựa khi vấp ngã · trường học đầu tiên (lễ phép, trung thực)." },
        { so: 3, ten: "Chọn dẫn chứng", de: "Một chuyện của chính Kim hoặc một nhân vật đã học.", vd: "Lần Kim ốm, mẹ thức đêm; hoặc gia đình An trong Đi lấy mật: tía nuôi, má nuôi dạy An cách sống với rừng." },
      ],
    },
    {
      ten: "Trong khi viết (20 phút)",
      doan: ["Viết liền một khối, lùi đầu dòng một lần. Dùng từ nối ở đầu mỗi ý: Trước hết / Không chỉ vậy / Hơn nữa / Nếu không có / Thế nhưng / Là một người con. Viết xong đếm câu, đối chiếu dãy 1–1–3–1–1–2 và câu “nếu không có”."],
      hop: { nhan: "Đưa tiếng Việt vào bài", chu: "Đặt một trạng ngữ được mở rộng ở câu dẫn chứng (“Mùa đông năm ngoái, khi em bị sốt cao,…”) và mở rộng chủ ngữ ở một câu ý (“Những người thân trong gia đình…”). Đề hay yêu cầu gạch chân, có sẵn thì khỏi loay hoay." },
    },
    {
      ten: "Sau khi viết (2 phút): bảng tự chấm 5 điểm",
      kn: [
        { ten: "Hình thức (1 điểm)", de: "Đúng đoạn văn, 10–12 câu, không xuống dòng, không sai chính tả nhiều.", vd: "Đủ: 1. Thiếu một điều: 0,5." },
        { ten: "Mở và giải thích (1 điểm)", de: "Có câu nêu vấn đề, có câu “gia đình là…”.", vd: "Đủ hai câu: 1." },
        { ten: "Ba ý có lí lẽ (1,5 điểm)", de: "Ba ý, mỗi ý có vế vì sao, có câu “nếu không có”.", vd: "Mỗi ý 0,5." },
        { ten: "Dẫn chứng và phản đề (1 điểm)", de: "Có ví dụ thật, có câu “Thế nhưng”.", vd: "Mỗi thứ 0,5." },
        { ten: "Bài học và kết (0,5 điểm)", de: "Việc làm cụ thể, câu kết khẳng định lại.", vd: "Đủ: 0,5." },
      ],
    },
  ],
  doiChieu: [
    ["Vai trò", "X quan trọng thế nào với ai"],
    ["Chỗ dựa", "Nơi ta tìm đến khi khó khăn"],
    ["Phản đề", "Câu Thế nhưng, phê phán điều ngược lại"],
    ["Bảng tự chấm", "Chia 5 điểm thành từng mục để tự soi bài"],
  ],
  meo: "Viết xong, đừng đọc lại từ đầu; hãy đếm: có mấy câu, có “là gì” chưa, có ba từ nối chưa, có “nếu không có” chưa, có “Thế nhưng” chưa, có việc cụ thể chưa. Sáu lần gật đầu là bài đủ ý.",
  tuKiemTra: [
    { q: "Đoạn mẫu để so sánh (khoảng 11 câu, 200 chữ)", a: "Gia đình có vai trò vô cùng quan trọng đối với mỗi người. Gia đình là nơi có ông bà, cha mẹ, anh chị em cùng chung sống và yêu thương nhau. Trước hết, gia đình là nơi ta được sinh ra, được chăm sóc từ bữa ăn đến giấc ngủ, nhờ đó ta lớn lên khỏe mạnh. Không chỉ vậy, gia đình là chỗ dựa vững chắc mỗi khi ta vấp ngã, vì dù ngoài kia có chuyện gì thì về nhà vẫn có người dang tay đón. Hơn nữa, những người thân trong gia đình chính là những người thầy đầu tiên dạy ta biết lễ phép, trung thực và yêu thương. Nếu không có gia đình, con người dễ cô đơn, thiếu chỗ dựa và khó vượt qua khó khăn. Mùa đông năm ngoái, khi em bị sốt cao, mẹ đã thức trắng đêm chườm khăn và bố đội mưa đi mua thuốc cho em. Chính lúc ấy em hiểu gia đình quý giá đến nhường nào. Thế nhưng, vẫn có những bạn xem nhẹ gia đình, cãi lời cha mẹ hay ít khi trò chuyện với ông bà, đó là điều đáng buồn. Là một người con, em sẽ phụ mẹ nấu cơm mỗi tối và gọi điện hỏi thăm ông bà mỗi tuần. Gia đình là điểm tựa để mỗi người vững bước trong cuộc đời." },
    { q: "Trong đoạn mẫu, câu nào là câu “nếu không có”? Trạng ngữ được mở rộng nằm ở câu nào?", a: "Câu 6: “Nếu không có gia đình, con người dễ cô đơn…”. Trạng ngữ mở rộng ở câu dẫn chứng: “Mùa đông năm ngoái, khi em bị sốt cao,”." },
    { q: "Chủ ngữ được mở rộng bằng cụm danh từ nằm ở câu nào?", a: "Câu 5: “Những người thân trong gia đình” là cụm danh từ làm chủ ngữ." },
    { q: "Kim tự chấm được bao nhiêu điểm theo bảng? Mục nào thấp nhất?", a: "Ghi vào vở. Mục thấp nhất là mục cần luyện lại trong bài ngày mai. Nếu mục ba ý thấp, đọc lại bài 30/09; nếu hình thức thấp, chú ý không xuống dòng và đếm câu." },
    { q: "Nếu đề đổi thành “ý nghĩa của gia đình”, Kim bỏ câu nào đi cũng được?", a: "Câu “Nếu không có gia đình…” có thể bỏ, vì đề ý nghĩa không đòi hỏi câu này. Còn lại giữ nguyên." },
  ],
};

/* ===== Thứ Sáu 02/10 · Đề thi thử hoàn chỉnh ===== */
window.KIM_GIANG["on-van-1002"] = {
  mon: "van",
  ngay: "2026-10-02",
  tieuDe: "Ôn Văn ngày 11 · Đề thi thử hoàn chỉnh 10 điểm, 45 phút",
  sgk: "Đề tự soạn theo cấu trúc: Đọc hiểu và Tiếng Việt 5 điểm · Viết 5 điểm",
  motCau: "Đây là buổi tổng duyệt. Kim làm như thi thật: bấm giờ 45 phút, viết ra giấy kiểm tra, không mở sách. Phần đọc hiểu làm trong 20 phút, phần viết 25 phút. Làm xong mới mở đáp án chấm, rồi ghi lại điểm và ba chỗ sai để mai ôn nốt.",
  phan: [
    {
      ten: "Phần I · Đọc hiểu và Tiếng Việt (5 điểm)",
      doan: [
        "Đọc văn bản sau:",
        "CHIẾC ÁO MƯA",
        "Tôi nhớ mãi buổi chiều mùa hạ năm lớp năm. Tan học, trời bỗng đổ mưa như trút nước. Cả sân trường nháo nhác, những chiếc áo mưa đủ màu nở bung như một vườn hoa vội vã. Tôi đứng nép dưới mái hiên, tay ôm chặt cặp sách, bụng đói cồn cào mà không biết làm sao về nhà.",
        "– Về chung không? – Tiếng Hùng vang lên phía sau. Hùng học cùng lớp nhưng tôi ít nói chuyện với cậu ấy, vì cậu hay ngồi một mình và chẳng bao giờ cười.",
        "Hùng giơ chiếc áo mưa ra, cái áo cũ đã sờn hai bên vai. Suốt quãng đường hai cây số dưới cơn mưa mỗi lúc một nặng hạt, cậu ấy đi bên ngoài, nhường tôi phần áo rộng hơn. Về đến ngõ, tôi mới thấy một bên vai Hùng ướt sũng, còn tôi thì gần như khô ráo.",
        "Hôm sau, tôi mang cho Hùng một hộp bánh mẹ làm. Cậu ấy cười, nụ cười đầu tiên tôi thấy sau cả một năm học. Từ hôm đó, chúng tôi thành bạn. Bây giờ mỗi khi trời đổ mưa, tôi lại nhớ tới chiếc áo mưa sờn vai và thấy lòng mình ấm lên.",
        "(Truyện ngắn tự sáng tác, dùng để luyện tập)",
        "Câu 1 (0,5 điểm). Văn bản kể theo ngôi thứ mấy? Nêu tác dụng của ngôi kể đó.",
        "Câu 2 (0,5 điểm). Nêu đề tài của văn bản.",
        "Câu 3 (1 điểm). Chỉ ra và nêu tác dụng của biện pháp tu từ trong câu: “Cả sân trường nháo nhác, những chiếc áo mưa đủ màu nở bung như một vườn hoa vội vã.”",
        "Câu 4 (1 điểm). Xác định trạng ngữ trong câu “Suốt quãng đường hai cây số dưới cơn mưa mỗi lúc một nặng hạt, cậu ấy đi bên ngoài, nhường tôi phần áo rộng hơn.” và cho biết trạng ngữ được mở rộng bằng cụm từ có tác dụng gì trong việc thể hiện nhân vật Hùng.",
        "Câu 5 (1 điểm). Chi tiết “một bên vai Hùng ướt sũng, còn tôi thì gần như khô ráo” cho em hiểu gì về nhân vật Hùng?",
        "Câu 6 (1 điểm). Từ văn bản, em rút ra bài học gì cho bản thân? Trình bày bằng 2–3 câu.",
      ],
    },
    {
      ten: "Phần II · Viết (5 điểm)",
      doan: ["Viết đoạn văn khoảng 10–12 câu trình bày suy nghĩ của em về ý nghĩa của lòng tốt trong cuộc sống. Trong đoạn văn có sử dụng một trạng ngữ được mở rộng bằng cụm từ (gạch chân)."],
      hop: { nhan: "Nhắc trước giờ làm", chu: "Phần viết chiếm một nửa số điểm. Dù đọc hiểu chưa xong, đến phút thứ 20 phải chuyển sang viết. Bỏ trống phần viết là mất 5 điểm, bỏ một câu đọc hiểu chỉ mất 1 điểm." },
    },
  ],
  doiChieu: [
    ["Phần I", "6 câu, 5 điểm, 20 phút"],
    ["Phần II", "1 đoạn văn, 5 điểm, 25 phút"],
    ["Gạch chân trạng ngữ", "Gạch trọn cụm, ghi (TN) bên cạnh"],
  ],
  meo: "Trước khi nộp, soát ba thứ: tên biện pháp tu từ có đúng không, câu bài học có đủ hai bài học không, đoạn văn có gạch chân trạng ngữ chưa. Ba chỗ này là ba chỗ Kim hay quên nhất.",
  tuKiemTra: [
    { q: "Đáp án câu 1", a: "Ngôi thứ nhất, người kể xưng “tôi”. Tác dụng: người kể trực tiếp trải qua câu chuyện nên bộc lộ được cảm xúc thật (lo lắng khi kẹt mưa, xúc động khi thấy vai bạn ướt), khiến câu chuyện chân thực, gần gũi." },
    { q: "Đáp án câu 2", a: "Đề tài: tình bạn (tình bạn tuổi học trò)." },
    { q: "Đáp án câu 3", a: "So sánh: những chiếc áo mưa đủ màu “như một vườn hoa vội vã” (có thể nêu thêm nhân hóa: áo mưa “nở bung”, vườn hoa “vội vã”). Tác dụng: làm cảnh sân trường lúc mưa hiện lên cụ thể, sinh động, gợi hình gợi cảm; người đọc hình dung sân trường rực rỡ sắc màu áo mưa như một vườn hoa đang nở, qua đó thấy cái nhìn tươi vui, đầy yêu mến của nhân vật tôi với những kỉ niệm tuổi học trò." },
    { q: "Đáp án câu 4", a: "Trạng ngữ: “Suốt quãng đường hai cây số dưới cơn mưa mỗi lúc một nặng hạt” (chỉ thời gian, nơi chốn và hoàn cảnh). Việc mở rộng bằng cụm từ cho biết cụ thể quãng đường dài, cơn mưa ngày càng to, nhờ đó làm nổi bật sự bền bỉ và tấm lòng nhường nhịn của Hùng: đi suốt chặng đường dài trong mưa lớn mà vẫn nhường bạn phần áo rộng." },
    { q: "Đáp án câu 5", a: "Hùng là người tốt bụng, biết quan tâm và sẵn sàng chịu thiệt về mình vì bạn. Cậu lặng lẽ đi bên ngoài để che mưa cho bạn mà không nói một lời. Bề ngoài ít nói, không hay cười nhưng bên trong Hùng rất ấm áp. Cần có đủ hai ý: tốt bụng, chịu thiệt vì bạn; và bề ngoài lạnh nhưng bên trong ấm." },
    { q: "Đáp án câu 6", a: "Ví dụ: Em học được rằng không nên đánh giá một người qua vẻ ngoài ít nói, vì như Hùng, họ có thể rất tốt bụng. Em cũng hiểu rằng một hành động nhỏ như nhường phần áo mưa có thể mở đầu cho một tình bạn đẹp. Vì vậy, em sẽ chủ động bắt chuyện và giúp đỡ những bạn hay ngồi một mình trong lớp." },
    { q: "Gợi ý phần viết: dàn ý và đoạn mẫu", a: "Dàn ý: Mở: lòng tốt là điều đẹp đẽ ai cũng cần có. Giải thích: lòng tốt là sẵn sàng giúp đỡ, chia sẻ với người khác mà không tính toán. Ba ý nghĩa: người được giúp vượt qua khó khăn; người trao đi thấy hạnh phúc; xã hội gắn bó, ấm áp hơn. Dẫn chứng: Hùng trong truyện Chiếc áo mưa, hoặc những đợt quyên góp giúp đồng bào vùng lũ. Mặt trái: Thế nhưng vẫn có người sống ích kỉ, thờ ơ trước khó khăn của người khác. Bài học: em sẽ giúp bạn giảng bài khi bạn chưa hiểu, nhường ghế cho người già trên xe buýt. Kết: lòng tốt làm cuộc sống đẹp hơn mỗi ngày. Đoạn mẫu: Lòng tốt là một trong những điều đẹp đẽ nhất mà mỗi người cần có trong cuộc sống. Lòng tốt là sẵn sàng giúp đỡ, chia sẻ với người khác bằng cả tấm lòng mà không tính toán thiệt hơn. Trước hết, lòng tốt giúp người gặp khó khăn có thêm sức mạnh để vượt qua, vì một bàn tay chìa ra đúng lúc quý hơn nhiều lời nói. Không chỉ vậy, người trao đi lòng tốt cũng thấy mình sống có ích và hạnh phúc hơn. Hơn nữa, khi ai cũng biết sống tốt với nhau, xã hội sẽ trở nên gắn bó và ấm áp. Trong một buổi chiều mưa tầm tã ở sân trường, cậu bạn Hùng trong truyện Chiếc áo mưa đã nhường phần áo rộng cho bạn và chịu ướt suốt quãng đường dài, để rồi từ đó hai người thành bạn thân. Ngoài đời, mỗi mùa lũ, hàng nghìn người lại góp tiền, góp gạo gửi về vùng bị thiệt hại. Thế nhưng, vẫn có những người sống ích kỉ, thờ ơ trước khó khăn của người khác, đó là điều đáng phê phán. Là học sinh, em sẽ giảng lại bài cho bạn khi bạn chưa hiểu và nhường ghế cho người già mỗi khi đi xe buýt. Lòng tốt không cần lớn lao, chỉ cần có thật, và nó sẽ làm cuộc sống của chúng ta đẹp hơn mỗi ngày. (Trạng ngữ gạch chân: “Trong một buổi chiều mưa tầm tã ở sân trường”.)" },
    { q: "Tổng điểm Kim tự chấm và ba chỗ sai cần ôn lại ngày mai", a: "Ghi vào vở: Đọc hiểu …/5, Viết …/5. Ba chỗ sai: … Ngày mai sẽ ôn đúng ba chỗ này." },
  ],
};

/* ===== Thứ Bảy 03/10 · Ôn nước rút ===== */
window.KIM_GIANG["on-van-1003"] = {
  mon: "van",
  ngay: "2026-10-03",
  tieuDe: "Ôn Văn ngày 12 · Nước rút: tờ ghi nhớ một trang và những lỗi hay mất điểm",
  sgk: "Tổng kết 11 ngày ôn · đọc lại trước ngày kiểm tra",
  motCau: "Hôm nay không làm đề, chỉ đọc lại một trang ghi nhớ và soát những lỗi hay mất điểm. Kim đọc chậm, chỗ nào đọc mà chưa tự nói lại được thì quay về bài của ngày đó. Cuối cùng làm 10 câu hỏi nhanh để chắc chắn mọi thứ đã nằm trong đầu.",
  phan: [
    {
      ten: "Tờ ghi nhớ một trang: đọc hiểu",
      kn: [
        { ten: "Ngôi kể", de: "Xưng tôi: ngôi thứ nhất, chân thực, bộc lộ cảm xúc. Gọi tên: ngôi thứ ba, bao quát, kể được nhiều người nhiều nơi.", vd: "Nhìn phần lời kể, không nhìn lời thoại." },
        { ten: "Đề tài", de: "Truyện viết về cái gì, trả lời bằng cụm từ.", vd: "Tình bạn / tình cảm gia đình / tuổi thơ và thiên nhiên." },
        { ten: "Chi tiết tiêu biểu", de: "Chi tiết che đi thì truyện nhạt. Nêu chi tiết + cho thấy điều gì.", vd: "Hai anh em khóc khi bầy chim bay lên → tình thương trong trẻo." },
        { ten: "Nhận xét nhân vật", de: "Việc làm trước, tính cách sau, 2–3 câu.", vd: "Mên cộc cằn bề ngoài nhưng ấm áp bên trong." },
        { ten: "Bài học", de: "Cần gì + vì sao, viết hai bài học.", vd: "Cần yêu thương loài vật, vì… Anh em cần đùm bọc nhau, vì…" },
      ],
    },
    {
      ten: "Tờ ghi nhớ một trang: tiếng Việt",
      kn: [
        { ten: "So sánh", de: "Có như / là / tựa, có A và B. Tác dụng: cụ thể, sinh động, gợi hình gợi cảm + hình dung gì, tình cảm gì.", vd: "Mặt trời như quả cầu lửa." },
        { ten: "Nhân hóa", de: "Vật làm người: gọi, tả, nói chuyện. Tác dụng: sinh động, gần gũi, có hồn + vật giống người ở chỗ nào, tình cảm gì.", vd: "Chị gió thì thầm." },
        { ten: "Ẩn dụ", de: "So sánh giấu vế A, từ đứng lạ chỗ. Tác dụng: hàm súc, gợi hình gợi cảm + B chỉ A, giống ở đâu, tình cảm gì.", vd: "Mặt trời trong lăng." },
        { ten: "Trạng ngữ", de: "Khi nào, ở đâu, vì sao, để làm gì. Mở rộng bằng cụm từ: thông tin cụ thể hơn, sự việc rõ ràng sinh động hơn.", vd: "Suốt từ chiều hôm qua," },
        { ten: "Mở rộng thành phần chính", de: "Chủ ngữ thành cụm danh từ, vị ngữ thành cụm động từ hoặc cụm tính từ. Cụm dài mấy vẫn là một thành phần.", vd: "Những chú chim sâu nhỏ xíu / đang hót líu lo trên cành bưởi." },
      ],
    },
    {
      ten: "Tờ ghi nhớ một trang: viết đoạn",
      doan: ["Dãy 1–1–3–1–1–2: mở, giải thích, ba ý có vì sao, dẫn chứng, Thế nhưng, bài học cụ thể và kết. Đề vai trò thêm câu “nếu không có”. Đề lợi ích thì ý phải cụ thể, nói được ta được gì. Một trạng ngữ mở rộng đặt ở câu dẫn chứng để gạch chân. Viết liền một khối, 10–12 câu."],
    },
    {
      ten: "Mười lỗi hay mất điểm (đọc kĩ)",
      buoc: [
        { so: 1, ten: "Nhìn lời thoại để xác định ngôi kể", de: "Lời thoại xưng em, tôi không tính.", vd: "Nhìn phần kể ngoài dấu gạch đầu dòng." },
        { so: 2, ten: "Hỏi đề tài, trả lời bài học", de: "Đề tài chỉ là cụm từ.", vd: "Tình bạn, không phải “cần quý trọng tình bạn”." },
        { so: 3, ten: "Tác dụng chỉ viết “làm câu văn hay hơn”", de: "Mất nửa điểm.", vd: "Phải có câu thuộc lòng + câu của mình." },
        { so: 4, ten: "Gọi nhầm so sánh với ẩn dụ", de: "Có “như” là so sánh. Không có “như”, từ lạ chỗ là ẩn dụ.", vd: "“Mẹ là ngọn gió” so sánh; “ngọn gió của con” ẩn dụ." },
        { so: 5, ten: "Gạch chân trạng ngữ thiếu chữ", de: "Gạch trọn cụm.", vd: "Gạch “Suốt từ chiều hôm qua”, không chỉ “hôm qua”." },
        { so: 6, ten: "Nhận xét nhân vật mà không dẫn việc làm", de: "Nói suông là không có điểm bằng chứng.", vd: "Thêm: cậu đã… (chi tiết)." },
        { so: 7, ten: "Bài học chỉ một câu, không có vì sao", de: "Viết hai bài học, mỗi bài có vế vì.", vd: "Cần …, vì … Bên cạnh đó, em cũng hiểu rằng …" },
        { so: 8, ten: "Đoạn văn xuống dòng, thành hai ba đoạn", de: "Trừ điểm hình thức.", vd: "Lùi đầu dòng một lần duy nhất." },
        { so: 9, ten: "Dẫn chứng kể dài nửa đoạn", de: "Dẫn chứng chỉ 1–2 câu.", vd: "Trong truyện X, nhân vật Y đã… Việc làm ấy khiến…" },
        { so: 10, ten: "Không còn giờ cho phần viết", de: "Phút 20 phải chuyển sang viết.", vd: "Phần viết là 5 điểm." },
      ],
    },
  ],
  doiChieu: [
    ["Câu thuộc lòng so sánh", "cụ thể, sinh động, gợi hình gợi cảm"],
    ["Câu thuộc lòng nhân hóa", "sinh động, gần gũi, có hồn"],
    ["Câu thuộc lòng ẩn dụ", "hàm súc, gợi hình gợi cảm, giàu sức gợi"],
    ["Câu thuộc lòng trạng ngữ mở rộng", "thông tin cụ thể hơn, sự việc rõ ràng sinh động hơn"],
    ["Câu thuộc lòng ngôi thứ nhất", "chân thực, gần gũi, bộc lộ cảm xúc"],
    ["Câu thuộc lòng ngôi thứ ba", "khách quan, linh hoạt, bao quát"],
  ],
  meo: "Tối trước ngày kiểm tra chỉ đọc lại ba tờ ghi nhớ ở trên và mười lỗi, rồi đi ngủ sớm. Vào phòng thi, việc đầu tiên là ghi lên nháp dãy 1–1–3–1–1–2 và ba câu thuộc lòng của ba biện pháp tu từ.",
  tuKiemTra: [
    { q: "1. Người kể gọi nhân vật là “cô bé”, “nó”. Ngôi kể nào, tác dụng gì?", a: "Ngôi thứ ba; khách quan, bao quát, kể được nhiều nhân vật, nhiều nơi và cả suy nghĩ bên trong của họ." },
    { q: "2. “Ông mặt trời đạp xe qua đỉnh núi.” Biện pháp gì?", a: "Nhân hóa (gọi “ông”, tả mặt trời đạp xe)." },
    { q: "3. “Lá vàng như những cánh bướm.” Biện pháp gì?", a: "So sánh." },
    { q: "4. “Những cánh bướm vàng lìa cành trong gió thu.” (nói về lá vàng) Biện pháp gì?", a: "Ẩn dụ: “cánh bướm vàng” chỉ lá vàng, giấu vế A." },
    { q: "5. Câu thuộc lòng tác dụng của ẩn dụ?", a: "Làm cách diễn đạt hàm súc, gợi hình, gợi cảm, giàu sức gợi." },
    { q: "6. Trạng ngữ trong “Để kịp giờ học, Lan dậy từ năm giờ sáng.” chỉ gì?", a: "“Để kịp giờ học” chỉ mục đích." },
    { q: "7. Mở rộng vị ngữ: “Bé cười.”", a: "Ví dụ: Bé / cười khanh khách khi thấy chú chó con chạy vào." },
    { q: "8. Dãy số của khung đoạn văn và ý nghĩa từng số?", a: "1–1–3–1–1–2: mở, giải thích, ba ý, dẫn chứng, phản đề, bài học và kết." },
    { q: "9. Đề “vai trò của thầy cô”: cần thêm câu gì?", a: "Câu “Nếu không có thầy cô, …”." },
    { q: "10. Đến phút bao nhiêu phải chuyển sang phần viết?", a: "Phút 20. Phần viết 5 điểm, không được bỏ." },
  ],
};
