/* SOẠN BÀI — học trước ở nhà, 10 phút mỗi bài, làm TRƯỚC tiết học trên lớp.
   Tách riêng file này để dễ sửa số trang / câu hỏi mà không đụng file tuần.
   Mỗi mục: mon (toan|van|anh|khtn|sudia), bai (tên bài), sgk (tập, trang), viec (các bước làm),
   cauHoi (2–3 câu Kim tự trả lời ngắn, gõ vào ô), nho (3–5 dòng cần nhớ).
   Số trang ghi theo SGK Kết nối tri thức; mẹ đối chiếu với sách rồi sửa nếu lệch. */
window.KIM_SOAN = window.KIM_SOAN || {};

window.KIM_SOAN[1] = [
  { mon: "van", soanToi: 2, hocVao: "Ngữ văn · sáng Thứ Ba", bai: "Bài 1 · Bầy chim chìa vôi (Nguyễn Quang Thiều)", sgk: "Ngữ văn 7 tập 1, tr. 9–17",
    viec: ["Đọc mục Tri thức ngữ văn (tr. 10): đề tài, chi tiết, tính cách nhân vật. Chép 3 khái niệm này vào vở soạn.", "Đọc hết văn bản Bầy chim chìa vôi, đọc chậm, vừa đọc vừa để ý các ô chỉ dẫn bên lề (theo dõi, hình dung, dự đoán).", "Gạch chân 3 chi tiết Kim thấy hay nhất về hai anh em Mon và Mên.", "Trả lời các câu hỏi Sau khi đọc (tr. 16) vào vở soạn, ngắn gọn 1–2 dòng mỗi câu."],
    cauHoi: ["Câu chuyện xảy ra trong hoàn cảnh nào (thời gian, thời tiết, ở đâu)?", "Kim thích chi tiết nào nhất? Vì sao?", "Nếu là Mon, Kim có rủ anh ra bãi sông lúc nửa đêm không?"],
    nho: ["Đề tài = phạm vi đời sống được phản ánh; chủ đề = vấn đề chính tác phẩm đặt ra.", "Chi tiết tiêu biểu là chi tiết nhỏ nhưng nói được nhiều điều về nhân vật và chủ đề.", "Tính cách nhân vật lộ ra qua lời nói, hành động, suy nghĩ, cách ứng xử.", "Truyện kể ngôi thứ ba; nhân vật Mon, Mên; đề tài tuổi thơ gắn với thiên nhiên."] },
  { mon: "toan", soanToi: 3, hocVao: "Toán · sáng Thứ Tư", bai: "Bài 1 · Tập hợp các số hữu tỉ", sgk: "Toán 7 tập 1, tr. 5–9",
    viec: ["Đọc phần 1 (Số hữu tỉ) và phần 2 (Biểu diễn trên trục số), tự làm các Hoạt động (HĐ) và Luyện tập trong bài.", "Ghi vào vở: định nghĩa số hữu tỉ, kí hiệu ℚ, cách so sánh hai số hữu tỉ.", "Thử tự trả lời: −3, 0,5, 2/7, 0 có phải số hữu tỉ không?"],
    cauHoi: ["Số hữu tỉ là số như thế nào? Viết bằng lời của Kim.", "Số −0,75 viết dưới dạng phân số là gì?", "Số nào lớn hơn: −1/2 hay −1/3? Vì sao?"],
    nho: ["Số hữu tỉ = số viết được dạng a/b, a và b nguyên, b ≠ 0. Số nguyên, số thập phân hữu hạn đều là số hữu tỉ.", "ℕ ⊂ ℤ ⊂ ℚ.", "So sánh: quy đồng mẫu dương rồi so sánh tử. Số âm càng gần 0 càng lớn.", "Trên trục số, số nhỏ hơn nằm bên trái."] },
  { mon: "toan", soanToi: 4, hocVao: "Toán · sáng Thứ Năm", bai: "Bài 8 · Góc ở vị trí đặc biệt. Tia phân giác của một góc", sgk: "Toán 7 tập 1, tr. 41–45",
    viec: ["Đọc phần 1: hai góc kề bù, hai góc đối đỉnh; vẽ lại hình minh hoạ vào vở.", "Đọc phần 2: tia phân giác; tự vẽ một góc 60° rồi vẽ tia phân giác bằng thước đo góc.", "Làm Luyện tập 1 và 2 trong bài."],
    cauHoi: ["Hai góc kề bù là gì? Tổng của chúng bằng bao nhiêu?", "Hai góc đối đỉnh có bằng nhau không?", "Góc 80° có tia phân giác thì chia thành hai góc bao nhiêu độ?"],
    nho: ["Kề bù: chung một cạnh, hai cạnh còn lại là hai tia đối nhau, tổng 180°.", "Đối đỉnh: mỗi cạnh góc này là tia đối của một cạnh góc kia; hai góc đối đỉnh bằng nhau.", "Tia phân giác chia góc thành hai góc bằng nhau."] },
  { mon: "anh", soanToi: 8, hocVao: "Tiếng Anh · chiều Thứ Hai", bai: "Unit 1 · Hobbies (Getting started, A closer look 1)", sgk: "Tiếng Anh 7 Global Success, tr. 8–11",
    viec: ["Đọc hội thoại Getting started (tr. 8), tra và chép các từ mới vào sổ từ vựng.", "Xem bảng từ ở A closer look 1: hobby, collect, gardening, making models… đọc to mỗi từ 3 lần.", "Nghe phần phát âm /ə/ và /ɜː/ nếu có file nghe (sachmem.vn), hoặc đọc theo ví dụ trong sách."],
    cauHoi: ["Kim viết 3 sở thích của mình bằng tiếng Anh (dùng V-ing).", "Từ nào trong bài Kim thấy khó nhớ nhất?"],
    nho: ["love / like / enjoy / hate + V-ing: I enjoy reading.", "hobby (sở thích), collect (sưu tầm), unusual (khác thường), creative (sáng tạo).", "/ə/ ngắn và nhẹ (about, sofa); /ɜː/ dài (bird, girl)."] },
  { mon: "khtn", soanToi: 8, hocVao: "KHTN · sáng Thứ Hai", bai: "Bài 1 · Phương pháp và kĩ năng học tập môn KHTN", sgk: "KHTN 7, tr. 6–13",
    viec: ["Đọc phần I: các bước của phương pháp tìm hiểu tự nhiên; chép 5 bước vào vở theo thứ tự.", "Đọc phần II: các kĩ năng (quan sát, phân loại, liên hệ, đo, dự báo); mỗi kĩ năng tự nghĩ một ví dụ ngoài sách.", "Xem hình dụng cụ đo thời gian hiện số và dao động kí, ghi tên và công dụng."],
    cauHoi: ["Năm bước của phương pháp tìm hiểu tự nhiên là gì?", "Kim hãy nêu một câu hỏi về tự nhiên mà Kim muốn tìm hiểu."],
    nho: ["Quan sát, đặt câu hỏi → giả thuyết → kế hoạch kiểm tra → thực hiện → kết luận.", "Giả thuyết là dự đoán có cơ sở, cần kiểm chứng.", "Báo cáo thực hành: mục đích, dụng cụ, cách làm, kết quả, kết luận."] },
  { mon: "sudia", soanToi: 3, hocVao: "Lịch sử sáng Thứ Hai · Địa lí sáng Thứ Tư", bai: "Lịch sử Bài 1 (tiết 1) · Địa lí Bài 1 (tiết 1–2) — Châu Âu", sgk: "Lịch sử và Địa lí 7: LS tr. 9–11, ĐL tr. 96–101",
    viec: ["Lịch sử: đọc mục 1 (sự hình thành các vương quốc phong kiến Tây Âu); ghi 3 ý: đế quốc Rô-ma sụp đổ năm nào, ai lập vương quốc mới, xã hội chia thành những tầng lớp nào.", "Địa lí: mở lược đồ tự nhiên châu Âu; tìm và ghi tên 3 dãy núi, 3 đồng bằng, 2 bán đảo lớn.", "Địa lí: đọc mục địa hình và khí hậu, ghi tên 3 đới khí hậu của châu Âu."],
    cauHoi: ["Vì sao nói châu Âu là một châu lục nhỏ nhưng có đường bờ biển rất dài?", "Xã hội Tây Âu sau khi Rô-ma sụp đổ gồm những tầng lớp nào?"],
    nho: ["Năm 476 đế quốc Tây Rô-ma sụp đổ; người Giéc-man lập các vương quốc phong kiến ở Tây Âu.", "Hai giai cấp mới: lãnh chúa phong kiến và nông nô.", "Châu Âu: bắc giáp Bắc Băng Dương, tây giáp Đại Tây Dương, nam giáp Địa Trung Hải, đông giáp châu Á; bờ biển bị cắt xẻ mạnh, nhiều bán đảo và vịnh biển.", "Địa hình: đồng bằng chiếm 2/3 diện tích; núi già ở bắc và trung, núi trẻ ở nam (dãy An-pơ)."] },
];

window.KIM_SOAN[2] = [
  { mon: "van", soanToi: 2, hocVao: "Ngữ văn · sáng Thứ Ba", bai: "Bài 1 · Đi lấy mật (trích Đất rừng phương Nam, Đoàn Giỏi)", sgk: "Ngữ văn 7 tập 1, tr. 18–24",
    viec: ["Đọc văn bản, để ý ba nhân vật An, Cò, tía nuôi; gạch chân những câu An miêu tả cảnh rừng.", "Tìm hiểu 'gác kèo ong' qua lời tía nuôi giải thích, ghi 2–3 dòng.", "Trả lời câu hỏi Sau khi đọc vào vở soạn.", "Xem trước Thực hành tiếng Việt tr. 17 và 24: mở rộng trạng ngữ."],
    cauHoi: ["Chuyến đi rừng được kể qua con mắt của ai? Điều đó có tác dụng gì?", "Kim ấn tượng với hình ảnh thiên nhiên nào trong bài?", "Đặt một câu có trạng ngữ là cụm từ (ví dụ mở đầu bằng 'Vào một buổi sáng…')."],
    nho: ["Ngôi kể thứ nhất (An) làm cảnh rừng hiện lên qua cảm nhận trực tiếp, sinh động.", "Nhân vật An: ham hiểu biết, quan sát tinh tế, hay so sánh với lời má nuôi kể.", "Trạng ngữ mở rộng bằng cụm từ giúp thông tin thời gian, nơi chốn, cách thức cụ thể hơn."] },
  { mon: "toan", soanToi: 3, hocVao: "Toán · sáng Thứ Tư", bai: "Bài 2 · Cộng, trừ, nhân, chia số hữu tỉ", sgk: "Toán 7 tập 1, tr. 10–14",
    viec: ["Đọc phần 1 (cộng, trừ) rồi tự làm HĐ và Luyện tập; đọc phần 2 (nhân, chia).", "Ghi vào vở quy tắc: cộng trừ thì quy đồng; nhân thì tử nhân tử, mẫu nhân mẫu; chia thì nhân nghịch đảo.", "Tự tính thử: −1/2 + 1/3, (−2/5) · (5/6)."],
    cauHoi: ["Muốn cộng hai số hữu tỉ viết dưới dạng phân số, làm thế nào?", "Kết quả của 3/4 − (−1/4) là bao nhiêu?", "Chỗ nào Kim thấy dễ nhầm nhất khi làm với số âm?"],
    nho: ["Trừ một số = cộng với số đối: a − b = a + (−b).", "Chia = nhân với nghịch đảo: a : (c/d) = a · (d/c).", "Tính chất giao hoán, kết hợp, phân phối vẫn đúng với số hữu tỉ; dùng để tính nhanh."] },
  { mon: "toan", soanToi: 4, hocVao: "Toán · sáng Thứ Năm", bai: "Bài 9 · Hai đường thẳng song song và dấu hiệu nhận biết", sgk: "Toán 7 tập 1, tr. 46–49",
    viec: ["Đọc phần 1: góc so le trong, góc đồng vị; vẽ lại hình 'đường thẳng c cắt a và b' và tô màu từng cặp góc.", "Đọc phần 2: dấu hiệu nhận biết hai đường thẳng song song; chép dấu hiệu vào vở.", "Đọc phần 3: cách vẽ đường thẳng song song bằng êke; thử vẽ."],
    cauHoi: ["Cặp góc so le trong nằm ở vị trí nào so với đường thẳng cắt?", "Nếu một cặp góc so le trong bằng nhau thì kết luận gì?"],
    nho: ["So le trong: khác phía cát tuyến, nằm trong hai đường thẳng. Đồng vị: cùng phía, một trong một ngoài.", "Dấu hiệu: cặp góc so le trong bằng nhau (hoặc đồng vị bằng nhau) ⇒ a ∥ b.", "Vẽ song song: đặt êke vào a, trượt dọc thước đến điểm M."] },
  { mon: "anh", soanToi: 8, hocVao: "Tiếng Anh · chiều Thứ Hai", bai: "Unit 1 · A closer look 2, Communication, Skills 1", sgk: "Tiếng Anh 7 Global Success, tr. 10–13",
    viec: ["Đọc khung ngữ pháp Present simple ở A closer look 2; chép cách thêm -s/-es và cách đặt câu hỏi với do/does.", "Đọc bài đọc ở Skills 1, gạch chân 5 từ mới và tra nghĩa.", "Viết 3 câu về sở thích của một người trong gia đình (he/she + V-s)."],
    cauHoi: ["Khi nào động từ thêm -s/-es?", "Viết câu phủ định: My brother / like / fishing.", "Bài đọc Skills 1 nói về sở thích gì?"],
    nho: ["He/she/it + V-s; phủ định doesn't + V nguyên mẫu; câu hỏi Does + S + V?", "Trạng từ tần suất đứng trước động từ thường, sau be.", "Từ -y sau phụ âm → -ies: study → studies."] },
  { mon: "khtn", soanToi: 8, hocVao: "KHTN · sáng Thứ Hai", bai: "Bài 2 · Nguyên tử", sgk: "KHTN 7, tr. 14–20",
    viec: ["Đọc phần I và II: mô hình nguyên tử; vẽ mô hình nguyên tử carbon (6p, 6n, 6e) vào vở, tô màu hạt nhân và các lớp electron.", "Ghi bảng: proton (+), neutron (0), electron (−); số p = số e.", "Đọc phần III: khối lượng nguyên tử tính bằng amu; thử tính khối lượng oxygen (8p, 8n)."],
    cauHoi: ["Nguyên tử gồm những phần nào? Hạt nào ở đâu?", "Vì sao nguyên tử trung hoà về điện?", "Lớp electron thứ nhất chứa tối đa mấy electron?"],
    nho: ["Hạt nhân (p, n) ở giữa, electron quay quanh theo lớp: lớp 1 tối đa 2e, lớp 2 tối đa 8e.", "Số p = số e = số hiệu nguyên tử.", "Khối lượng nguyên tử ≈ số p + số n (amu)."] },
  { mon: "sudia", soanToi: 3, hocVao: "Lịch sử sáng Thứ Hai · Địa lí sáng Thứ Tư", bai: "Lịch sử Bài 1 (tiết 2) · Địa lí hết Bài 1, vào Bài 2 — Dân cư châu Âu", sgk: "Lịch sử và Địa lí 7: LS tr. 11–13, ĐL tr. 99–104",
    viec: ["Lịch sử: đọc mục lãnh địa phong kiến; vẽ sơ đồ đơn giản một lãnh địa (lâu đài, ruộng đất, nhà nông nô) và ghi ai làm gì.", "Địa lí: đọc nốt Bài 1 (sông ngòi, các đới thiên nhiên); ghi tên sông dài nhất và sông chảy qua nhiều nước nhất.", "Địa lí: đọc Bài 2 mục dân số; xem bảng số liệu và ghi 2 nhận xét."],
    cauHoi: ["Lãnh địa phong kiến là gì? Vì sao gọi là nền kinh tế khép kín?", "Vì sao nói dân số châu Âu đang già đi?"],
    nho: ["Lãnh địa: vùng đất riêng của lãnh chúa, có lâu đài, ruộng đất, nhà nông nô; kinh tế tự cung tự cấp, khép kín.", "Nông nô nhận ruộng của lãnh chúa, nộp tô và bị lệ thuộc; lãnh chúa sống bằng bóc lột nông nô.", "Sông Vôn-ga dài nhất châu Âu; sông Đa-nuýp chảy qua nhiều nước nhất.", "Dân số châu Âu tăng chậm, tỉ lệ người trên 65 tuổi cao và tăng, thiếu lao động nên phải nhận nhập cư."] },
];

window.KIM_SOAN[3] = [
  { mon: "van", soanToi: 2, hocVao: "Ngữ văn · sáng Thứ Ba", bai: "Bài 1 · Ngàn sao làm việc (Võ Quảng) · Viết: Tóm tắt văn bản", sgk: "Ngữ văn 7 tập 1, tr. 25–32",
    viec: ["Đọc bài thơ 2 lần, lần 2 đọc thành tiếng để nghe nhịp. Gạch chân các hình ảnh sao được nhân hoá.", "Đọc phần Viết (tr. 27): các bước tóm tắt văn bản; chép 4 yêu cầu của bản tóm tắt.", "Thử tóm tắt Bầy chim chìa vôi trong 3–4 câu vào vở soạn."],
    cauHoi: ["Bài thơ tưởng tượng bầu trời đêm giống như gì?", "Bản tóm tắt Bầy chim chìa vôi của Kim gồm những sự việc nào?", "Khi tóm tắt, điều gì KHÔNG được làm?"],
    nho: ["Thơ 5 chữ, nhân hoá: sao Thần Nông tung lưới, sao Hôm gánh nước… bầu trời như cánh đồng lao động.", "Tóm tắt: giữ nhân vật và sự việc chính, đúng thứ tự, ngắn hơn, không thêm ý kiến riêng.", "Thành phần chính của câu = chủ ngữ + vị ngữ; có thể mở rộng bằng cụm từ."] },
  { mon: "toan", soanToi: 3, hocVao: "Toán · sáng Thứ Tư", bai: "Bài 3 · Luỹ thừa với số mũ tự nhiên của một số hữu tỉ", sgk: "Toán 7 tập 1, tr. 16–20",
    viec: ["Đọc phần 1: định nghĩa x^n; tự tính (−1/2)^3 và (2/3)^2.", "Đọc phần 2 và 3: nhân, chia hai luỹ thừa cùng cơ số; luỹ thừa của luỹ thừa. Chép 3 công thức vào vở, mỗi công thức kèm 1 ví dụ số.", "Làm các Luyện tập trong bài."],
    cauHoi: ["x^3 · x^2 bằng gì? Vì sao không phải x^6?", "(−1)^10 và (−1)^11 bằng bao nhiêu?", "Công thức nào Kim thấy dễ nhầm nhất?"],
    nho: ["x^m · x^n = x^(m+n); x^m : x^n = x^(m−n); (x^m)^n = x^(m·n).", "(a/b)^n = a^n / b^n.", "Số âm mũ chẵn → dương; mũ lẻ → âm. x^0 = 1 (x ≠ 0)."] },
  { mon: "toan", soanToi: 4, hocVao: "Toán · sáng Thứ Năm", bai: "Bài 10 · Tiên đề Euclid. Tính chất của hai đường thẳng song song", sgk: "Toán 7 tập 1, tr. 51–54",
    viec: ["Đọc tiên đề Euclid, chép nguyên văn vào vở và vẽ hình minh hoạ.", "Đọc phần 2: tính chất hai đường thẳng song song (so le trong bằng nhau, đồng vị bằng nhau, trong cùng phía bù nhau).", "So sánh với Bài 9: dấu hiệu (từ góc suy ra song song) và tính chất (từ song song suy ra góc) ngược chiều nhau."],
    cauHoi: ["Qua một điểm nằm ngoài đường thẳng có mấy đường thẳng song song với nó?", "a ∥ b, một góc so le trong bằng 50°, góc kia bằng bao nhiêu?", "Hai góc trong cùng phía của hai đường thẳng song song có quan hệ gì?"],
    nho: ["Tiên đề Euclid: qua điểm M ngoài a, có đúng một đường thẳng song song với a.", "a ∥ b ⇒ so le trong bằng nhau, đồng vị bằng nhau, trong cùng phía bù nhau.", "Hai đường thẳng cùng song song (hoặc cùng vuông góc) với đường thứ ba thì song song với nhau."] },
  { mon: "anh", soanToi: 8, hocVao: "Tiếng Anh · chiều Thứ Hai", bai: "Unit 1 · Looking back & Project · Unit 2 · Healthy living (Getting started, A closer look 1)", sgk: "Tiếng Anh 7 Global Success, tr. 14–21",
    viec: ["Làm phần Looking back Unit 1 vào vở (từ vựng, ngữ pháp).", "Đọc hội thoại Getting started Unit 2; tra từ mới về sức khoẻ: sore throat, sunburn, spots, put on weight, keep fit.", "Đọc bảng từ A closer look 1 và tập phát âm /f/ – /v/ (fan – van)."],
    cauHoi: ["Kim viết 3 vấn đề sức khoẻ và 3 lời khuyên tương ứng bằng tiếng Anh.", "Từ nào có âm /v/: fine, very, phone?"],
    nho: ["Vấn đề – lời khuyên: sore throat → drink warm water; sunburn → put on sun cream; tired → sleep more.", "/f/ không rung (fan, fine, phone); /v/ rung dây thanh (van, very, view).", "keep fit = giữ sức khoẻ; junk food = đồ ăn vặt không tốt."] },
  { mon: "khtn", soanToi: 8, hocVao: "KHTN · sáng Thứ Hai", bai: "Bài 3 · Nguyên tố hoá học", sgk: "KHTN 7, tr. 21–25",
    viec: ["Đọc phần I: khái niệm nguyên tố hoá học; ghi câu định nghĩa.", "Đọc phần II: tên và kí hiệu hoá học; chép bảng 20 nguyên tố đầu vào vở, che tên rồi tự đọc kí hiệu.", "Đọc phần III: nguyên tố phổ biến trong vỏ Trái Đất và cơ thể người."],
    cauHoi: ["Hai nguyên tử thuộc cùng một nguyên tố khi nào?", "Viết kí hiệu của: hydrogen, carbon, sodium, chlorine, calcium.", "Nguyên tố nào nhiều nhất trong vỏ Trái Đất?"],
    nho: ["Nguyên tố hoá học = tập hợp nguyên tử cùng số proton.", "Kí hiệu 1–2 chữ cái, chữ đầu in hoa: H, C, N, O, Na, Mg, Al, Si, P, S, Cl, K, Ca, Fe, Cu, Zn.", "Oxygen chiếm gần một nửa khối lượng vỏ Trái Đất."] },
  { mon: "sudia", soanToi: 3, hocVao: "Lịch sử sáng Thứ Hai · Địa lí sáng Thứ Tư", bai: "Lịch sử Bài 1 (tiết 3) · Địa lí hết Bài 2, vào Bài 3 — Bảo vệ thiên nhiên", sgk: "Lịch sử và Địa lí 7: LS tr. 13–14, ĐL tr. 104–108",
    viec: ["Lịch sử: đọc mục thành thị trung đại; ghi 3 ý: thành thị ra đời thế nào, ai sống trong đó, có vai trò gì.", "Địa lí: đọc nốt Bài 2 (đô thị hoá, di cư); ghi tỉ lệ dân đô thị của châu Âu.", "Địa lí: đọc Bài 3 mục bảo vệ môi trường không khí và nước; mỗi mục ghi 2 biện pháp."],
    cauHoi: ["Thành thị trung đại có vai trò gì đối với kinh tế Tây Âu?", "Châu Âu làm gì để bảo vệ môi trường không khí?"],
    nho: ["Từ thế kỉ XI, sản xuất phát triển, thợ thủ công và thương nhân lập thành thị; thành thị làm kinh tế hàng hoá phát triển, phá vỡ nền kinh tế khép kín của lãnh địa.", "Thành thị còn là nơi ra đời các trường đại học đầu tiên.", "Châu Âu đô thị hoá sớm, trên 75% dân sống ở đô thị; đô thị hoá nông thôn phát triển.", "Bảo vệ môi trường: giảm khí thải, dùng năng lượng tái tạo, xử lí nước thải, kiểm soát đầu ra chất thải."] },
];

window.KIM_SOAN[4] = [
  { mon: "van", soanToi: 2, hocVao: "Ngữ văn · sáng Thứ Ba", bai: "Bài 2 · Đồng dao mùa xuân (Nguyễn Khoa Điềm)", sgk: "Ngữ văn 7 tập 1, tr. 39–42",
    viec: ["Đọc Tri thức ngữ văn Bài 2 (tr. 39): thơ bốn chữ, năm chữ; vần, nhịp, hình ảnh. Chép định nghĩa vần chân, vần lưng.", "Đọc bài thơ 3 lần: lần 1 đọc hiểu, lần 2 đọc thành tiếng theo nhịp 2/2, lần 3 tìm các tiếng gieo vần.", "Trả lời câu hỏi Sau khi đọc; chú ý câu hỏi về hình ảnh người lính."],
    cauHoi: ["Bài thơ nói về ai? Người đó có số phận thế nào?", "Tìm 2 cặp tiếng gieo vần trong bài.", "Kim cảm thấy gì khi đọc bài thơ này?"],
    nho: ["Thơ 4 chữ: mỗi dòng 4 tiếng, nhịp 2/2, vần chân hoặc vần lưng.", "Bài thơ viết về người lính trẻ hi sinh ở Trường Sơn, giọng đồng dao nhẹ nhàng mà xót xa.", "Cảm xúc: thương nhớ, biết ơn người đã ngã xuống cho mùa xuân đất nước."] },
  { mon: "toan", soanToi: 3, hocVao: "Toán · sáng Thứ Tư", bai: "Bài 4 · Thứ tự thực hiện các phép tính. Quy tắc chuyển vế", sgk: "Toán 7 tập 1, tr. 21–24",
    viec: ["Đọc phần 1: thứ tự thực hiện phép tính; chép sơ đồ ngoặc → luỹ thừa → nhân chia → cộng trừ.", "Đọc phần 2: quy tắc chuyển vế; chép quy tắc và ví dụ tìm x.", "Tự làm: 2 + 3·(−4) và tìm x biết x + 3/4 = 1/2."],
    cauHoi: ["Trong biểu thức có ngoặc và luỹ thừa, làm gì trước?", "Chuyển một số hạng sang vế kia thì dấu của nó thế nào?", "x − 2/5 = −1/5 thì x bằng bao nhiêu?"],
    nho: ["Ngoặc () → [] → {}; trong mỗi cấp: luỹ thừa → nhân chia → cộng trừ, trái sang phải.", "Chuyển vế đổi dấu: x + a = b ⇒ x = b − a.", "Tìm x xong nên thử lại bằng cách thay vào."] },
  { mon: "toan", soanToi: 4, hocVao: "Toán · sáng Thứ Năm", bai: "Bài 11 · Định lí và chứng minh định lí", sgk: "Toán 7 tập 1, tr. 56–58",
    viec: ["Đọc phần 1: định lí là gì, giả thiết và kết luận; lấy 2 định lí đã học (Bài 8, Bài 10) viết dưới dạng GT – KL.", "Đọc ví dụ chứng minh trong sách, để ý mỗi bước đều có 'vì…' (căn cứ).", "Thử tự chứng minh: hai góc đối đỉnh thì bằng nhau (dựa vào góc kề bù)."],
    cauHoi: ["Định lí gồm hai phần nào?", "Chứng minh định lí khác gì với đo hình rồi kết luận?", "Viết GT, KL của 'Nếu a ∥ b và c ⊥ a thì c ⊥ b'."],
    nho: ["Định lí: Nếu (GT) thì (KL). Tiên đề thì thừa nhận, định lí thì phải chứng minh.", "Chứng minh = chuỗi suy luận từ GT đến KL, mỗi bước có căn cứ.", "Ghi bài chứng minh: vẽ hình, ghi GT – KL, rồi trình bày từng bước."] },
  { mon: "anh", soanToi: 8, hocVao: "Tiếng Anh · chiều Thứ Hai", bai: "Unit 2 · A closer look 2, Communication, Skills 1", sgk: "Tiếng Anh 7 Global Success, tr. 20–23",
    viec: ["Đọc khung Simple sentences ở A closer look 2; chép 3 mẫu S + V, S + V + O, S + V + A, mỗi mẫu 1 ví dụ của Kim.", "Đọc Communication: cách hỏi thăm sức khoẻ và khuyên (should / shouldn't).", "Đọc bài đọc Skills 1 về thói quen lành mạnh, gạch chân 5 từ mới."],
    cauHoi: ["Câu 'Kim eats vegetables.' thuộc mẫu nào?", "Viết 2 lời khuyên bằng should / shouldn't.", "Bài đọc Skills 1 khuyên điều gì?"],
    nho: ["Câu đơn: một chủ ngữ + một động từ chính; có thể có tân ngữ hoặc trạng ngữ.", "should + V = nên; shouldn't + V = không nên.", "Don't + V: câu mệnh lệnh phủ định (Don't eat too much sugar)."] },
  { mon: "khtn", soanToi: 8, hocVao: "KHTN · sáng Thứ Hai", bai: "Bài 4 · Sơ lược về bảng tuần hoàn các nguyên tố hoá học", sgk: "KHTN 7, tr. 26–33",
    viec: ["Mở bảng tuần hoàn (trang gấp cuối sách hoặc tr. 27), tìm ô của O, Na, Cl; ghi số hiệu, kí hiệu, khối lượng.", "Đọc phần II: chu kì (hàng), nhóm (cột); ghi quy tắc: số chu kì = số lớp e, số nhóm A = số e lớp ngoài.", "Đọc phần III: vị trí kim loại, phi kim, khí hiếm; tô 3 màu lên bảng vẽ tay."],
    cauHoi: ["Bảng tuần hoàn sắp xếp theo nguyên tắc gì?", "Na có 11 electron xếp 2 – 8 – 1: Na ở chu kì mấy, nhóm mấy?", "Khí hiếm ở nhóm nào?"],
    nho: ["Sắp theo chiều tăng số proton (số hiệu nguyên tử).", "Chu kì = hàng ngang = số lớp electron; nhóm A = cột dọc = số e lớp ngoài cùng.", "Kim loại: trái và giữa; phi kim: phải; khí hiếm: nhóm VIIIA."] },
  { mon: "sudia", soanToi: 3, hocVao: "Lịch sử sáng Thứ Hai · Địa lí sáng Thứ Tư", bai: "Lịch sử Bài 2 (tiết 1) · Địa lí hết Bài 3, vào Bài 4 — Liên minh châu Âu", sgk: "Lịch sử và Địa lí 7: LS tr. 15–17, ĐL tr. 107–111",
    viec: ["Lịch sử: đọc mục nguyên nhân và các cuộc phát kiến; mở lược đồ, dùng 4 màu tô 4 hành trình và ghi năm bên cạnh.", "Địa lí: đọc nốt Bài 3 (bảo vệ đa dạng sinh học); ghi 2 biện pháp.", "Địa lí: đọc Bài 4 mục EU; ghi năm thành lập, số nước thành viên hiện nay."],
    cauHoi: ["Vì sao người châu Âu thế kỉ XV muốn tìm đường biển sang phương Đông?", "Bốn cuộc phát kiến lớn do ai thực hiện, vào năm nào?", "EU là gì? Vì sao các nước lại liên kết với nhau?"],
    nho: ["Nguyên nhân phát kiến: cần hương liệu, vàng bạc; đường bộ sang phương Đông bị chặn; đã có la bàn và tàu ca-ra-ven.", "1487 Đi-a-xơ đến mũi Hảo Vọng; 1492 Cô-lôm-bô đến châu Mỹ; 1498 Va-xcô đơ Ga-ma đến Ấn Độ; 1519–1522 Ma-gien-lăng đi vòng quanh Trái Đất.", "EU thành lập năm 1993 (tiền thân từ 1957), là liên minh kinh tế và chính trị, không phải một quốc gia.", "EU có thị trường chung, đồng tiền chung ơ-rô, tự do đi lại giữa nhiều nước thành viên."] },
];
