/* PHẦN THƯỞNG CUỐI NGÀY — mở khi Kim làm xong hết việc trong ngày.
   Gồm: một câu động viên + một mẩu tin Anh trai vượt ngàn chông gai + thẻ cào 5.000–20.000đ.

   Hai kho dưới đây được dùng lần lượt (không lặp lại cho tới khi hết kho), nên cứ vài tuần
   mẹ nhờ Claude bổ sung tin mới là được. Tin trong kho cập nhật đến 30/08/2026 (Công diễn 3).
   Chương trình phát 20h thứ Bảy trên VTV3, 20h30 trên YouTube Yeah1 Show. */

window.KIM_DONG_VIEN = [
  "Hôm nay Kim làm xong rồi. Việc nhỏ làm đều mỗi ngày sẽ thành việc lớn.",
  "Học không phải để giỏi ngay, mà để hôm nay hiểu hơn hôm qua một chút.",
  "Kim vừa giữ đúng lời hẹn với chính mình. Đó mới là điều khó nhất.",
  "Không ai nhớ bài chỉ sau một lần đọc. Kim đọc lại là Kim đang làm đúng cách.",
  "Sai một câu hôm nay để mai không sai trong bài kiểm tra. Xứng đáng lắm.",
  "Người học đều mỗi ngày sẽ vượt người học dồn một đêm. Kim đang chọn cách đúng.",
  "Mẹ không mong Kim điểm cao ngay, mẹ mong Kim thấy mình hiểu bài.",
  "Bộ não nhớ lâu nhất những gì mình tự nghĩ ra. Hôm nay Kim đã tự nghĩ.",
  "Có hôm học thấy dễ, có hôm thấy khó. Cả hai đều là đang tiến lên.",
  "Kim vừa cho ngày mai một món quà: ngày mai vào lớp sẽ nhẹ hơn.",
  "Chăm chỉ không ồn ào. Nó chỉ lặng lẽ làm Kim khá lên từng ngày.",
  "Câu nào chưa hiểu cứ để đó, cuối tuần mẹ con mình gỡ cùng nhau.",
  "Một trang sách đọc kĩ hơn mười trang đọc lướt.",
  "Kim của tuần sau sẽ cảm ơn Kim của tối nay.",
  "Không cần học nhiều, chỉ cần học thật. Hôm nay Kim học thật.",
  "Điều làm nên học sinh giỏi không phải trí thông minh, mà là thói quen.",
  "Mỗi lần Kim ngồi vào bàn học là một lần Kim thắng sự lười.",
  "Hiểu chậm mà chắc còn hơn thuộc nhanh rồi quên.",
  "Kim đang xây một thói quen. Thói quen thì bền hơn cảm hứng nhiều.",
  "Hôm nay có thể chưa thấy khác gì. Nhưng ba tháng nữa thì rất khác.",
  "Điểm số rồi sẽ quên, cách học thì theo Kim suốt đời.",
  "Đọc trước bài rồi vào lớp, Kim sẽ thấy cô giảng dễ hiểu hẳn.",
  "Người dám hỏi 'vì sao' là người học nhanh nhất lớp.",
  "Kim làm được nhiều hơn Kim nghĩ đấy.",
  "Kiên trì không phải là không mệt, mà là mệt rồi vẫn làm nốt.",
  "Tối nay xong việc rồi, Kim nghỉ ngơi cho thật thoải mái nhé.",
  "Mỗi câu sai là một chỗ Kim vừa tìm ra để sửa. Tìm được là tốt rồi.",
  "Học giống tập đàn: ngày nào cũng chạm vào thì tay mới quen.",
  "Không so với bạn nào cả. Chỉ cần hơn Kim của hôm qua.",
  "Việc khó làm đều thì thành dễ. Việc dễ bỏ lâu thì thành khó.",
  "Mẹ thấy Kim ngày càng tự giác hơn. Mẹ vui vì điều đó.",
  "Đầu óc cần ngủ đủ mới nhớ bài. Học xong là đi ngủ sớm nhé Kim.",
  "Bài hôm nay khó thì mai sẽ dễ hơn, vì hôm nay Kim đã đụng vào nó rồi.",
  "Không phải ngày nào cũng hứng thú học. Nhưng ngày nào cũng có thể bắt đầu.",
  "Chỗ Kim thấy khó nhất thường là chỗ Kim sắp giỏi lên.",
  "Kim vừa học xong. Giờ là lúc được thưởng đàng hoàng.",
  "Học đều như tưới cây: không thấy cây lớn từng ngày, nhưng rồi cây sẽ cao.",
  "Ghi vào vở bằng tay giúp nhớ lâu hơn đọc bằng mắt. Kim làm tốt lắm.",
  "Một ngày học tử tế đáng giá hơn ba ngày học qua loa.",
  "Cứ đi từng bước nhỏ. Đường dài là do nhiều bước nhỏ cộng lại.",
];

window.KIM_TIN = [
  { tieuDe: "Mùa mới đã khởi động từ 27/6/2026",
    noiDung: "Anh trai vượt ngàn chông gai 2026 lên sóng tập đầu ngày 27/6, phát 20h thứ Bảy trên VTV3 và 20h30 trên YouTube Yeah1 Show. Ngay tập mở màn đã có 17 ca khúc chào sân cho Công diễn Hội ngộ." },
  { tieuDe: "34 anh tài cùng tranh tài",
    noiDung: "Mùa này quy tụ 34 anh tài, đông hơn hẳn các mùa trước. Có ca sĩ, nhạc sĩ, diễn viên, MC, người mẫu — mỗi người một nghề, gặp nhau trên cùng một sân khấu âm nhạc." },
  { tieuDe: "Bảy sân khấu cho cả hành trình",
    noiDung: "Chương trình đi qua 7 sân khấu: một đêm Hội ngộ, năm vòng Công diễn và đêm Chung kết. Muốn tới cuối chặng, các anh tài phải giữ phong độ suốt nhiều tháng liền — giống như học đều cả học kì vậy." },
  { tieuDe: "Danh hiệu Chiến tướng lần đầu xuất hiện",
    noiDung: "Năm nay chương trình có thêm danh hiệu 'Chiến tướng', trao sau mỗi công diễn cho người thể hiện nổi bật nhất. Đây là điểm mới so với những mùa trước." },
  { tieuDe: "It's Charles giành Chiến tướng Công diễn 3",
    noiDung: "Ở Công diễn 3 phát sóng ngày 30/8/2026, It's Charles (tên thật Huỳnh Phương Duy) là người chiến thắng. Đây là cái tên còn khá mới với khán giả nhưng đã tạo bất ngờ lớn." },
  { tieuDe: "Bốn anh tài chia tay sau Công diễn 3",
    noiDung: "Nhạc sĩ Nguyễn Văn Chung, MC Đại Nghĩa, Phùng Minh Cương và Neko Lê đã dừng chân sau Công diễn 3 ngày 30/8. Cuộc chơi càng về sau càng khó, ai cũng phải cố hết sức." },
  { tieuDe: "Nhà Hợp Lực và bản retro thập niên 1990",
    noiDung: "Ở Công diễn 3, Nhà Hợp Lực mang lên sân khấu tiết mục 'Những năm tháng ấy' theo phong cách retro những năm 1990, do Thái VG làm thủ lĩnh cùng Đinh Mạnh Ninh, Trịnh Thăng Bình, Nguyễn Văn Chung và Tùng Mint." },
  { tieuDe: "Tập 3 từng phải hoãn một tuần",
    noiDung: "Tập 3 dự kiến phát 11/7 nhưng được dời sang 20h ngày 18/7 trên VTV3, sau khi tập 2 gặp tranh cãi kết quả và sự cố kĩ thuật. Làm chương trình lớn cũng có lúc trục trặc, quan trọng là sửa rồi đi tiếp." },
  { tieuDe: "Nguyễn Văn Chung — người viết bài hát trẻ em",
    noiDung: "Nguyễn Văn Chung là nhạc sĩ đã viết hàng trăm ca khúc thiếu nhi bên cạnh những bản nhạc trẻ nổi tiếng. Anh tham gia mùa này ở tuổi không còn trẻ so với dàn thí sinh, và đi được tới Công diễn 3." },
  { tieuDe: "Da LAB góp mặt hai thành viên",
    noiDung: "Nhóm Da LAB có hai thành viên cùng tham gia mùa 2026 là Thỏ và Thơm. Cùng một nhóm nhạc nhưng vào chương trình thì mỗi người tự lo phần mình." },
  { tieuDe: "BB Trần, Huỳnh Lập, Duy Khánh — dân diễn hài đi hát",
    noiDung: "Mùa này có nhiều nghệ sĩ vốn nổi tiếng ở mảng hài và diễn xuất như BB Trần, Huỳnh Lập, Duy Khánh, Neko Lê. Họ phải học hát, học vũ đạo từ đầu để đứng chung sân khấu với các ca sĩ chuyên nghiệp." },
  { tieuDe: "Hoàng Rob mang violin lên sân khấu",
    noiDung: "Hoàng Rob là nghệ sĩ violin, một màu sắc rất khác giữa dàn ca sĩ và rapper. Anh cho thấy nhạc cụ cổ điển vẫn có chỗ đứng trong một chương trình giải trí hiện đại." },
  { tieuDe: "Yeah1 tiếp tục là nhà sản xuất",
    noiDung: "Chương trình do tập đoàn Yeah1 sản xuất, dưới sự điều hành của Tổng Giám đốc Ngô Thị Vân Hạnh. Đây cũng là đơn vị làm nên thành công của những mùa trước." },
  { tieuDe: "Cái tên nói lên tất cả",
    noiDung: "'Vượt ngàn chông gai' — tên chương trình chính là tinh thần của nó: ai cũng có lúc hát chưa hay, tập chưa thuộc, bị loại giữa chừng. Điều đáng nể là vẫn tập tiếp vào hôm sau." },
  { tieuDe: "Trống Cơm — cú hích của mùa đầu tiên",
    noiDung: "Ở mùa 2024, tiết mục 'Trống Cơm' do Tự Long, Soobin và Cường Seven thể hiện đã gây sốt khắp mạng xã hội, làm nhiều bạn trẻ quay lại nghe nhạc dân gian. Một bài hát cũ vẫn có thể sống lại nếu được làm mới đúng cách." },
  { tieuDe: "Các nhà được lập rồi lại tan",
    noiDung: "Sau mỗi công diễn, các anh tài lại chia thành những 'nhà' mới. Có người vừa là đồng đội vòng này, vòng sau đã ở nhà khác. Học cách hợp tác nhanh với người mới cũng là một kĩ năng." },
  { tieuDe: "Biệt Đội Tái Xuất — nhóm của những người trở lại",
    noiDung: "Một trong những nhà được nhắc nhiều mùa này là Biệt Đội Tái Xuất, với BB Trần, Jun Phạm, Thanh Duy, Duy Khánh và Neko Lê. Tên nhà cũng là câu chuyện của họ: quay lại sân khấu sau thời gian vắng bóng." },
  { tieuDe: "Nhà Soạn Nhạc — nơi của người viết bài",
    noiDung: "Nhà Soạn Nhạc gồm Hồ Đông Quan, Thỏ, Hoàng Tôn, Osad và Hà An Huy. Đây là những người quen ngồi viết nhạc sau hậu trường, nay phải tự đứng ra biểu diễn bài của chính mình." },
  { tieuDe: "Hoàng Dũng — giọng ca của những bản ballad buồn",
    noiDung: "Hoàng Dũng được biết đến với các bản ballad nhẹ nhàng, sâu lắng. Vào một chương trình cần vũ đạo và sân khấu lớn, anh phải bước ra khỏi vùng quen thuộc của mình." },
  { tieuDe: "Tập luyện nhiều hơn biểu diễn rất nhiều",
    noiDung: "Mỗi tiết mục chỉ dài vài phút trên sóng, nhưng phía sau là hàng tuần tập hát, tập vũ đạo, dựng sân khấu. Cái Kim thấy trên tivi luôn là phần nhỏ nhất của công sức bỏ ra." },
  { tieuDe: "Trịnh Thăng Bình — vừa hát vừa viết nhạc",
    noiDung: "Trịnh Thăng Bình vừa là ca sĩ vừa là nhạc sĩ, tự sáng tác nhiều bài hát của mình. Ở chương trình, anh vừa phải lo phần trình diễn vừa góp ý cho cả nhóm." },
  { tieuDe: "Điểm hoả lực quyết định ai đi tiếp",
    noiDung: "Không chỉ nhà nào thắng mới an toàn: mỗi anh tài còn có điểm cá nhân riêng. Ai không đủ điểm sẽ phải dừng lại, dù đồng đội có làm tốt đến đâu. Nỗ lực của từng người đều được tính." },
  { tieuDe: "Từ sân khấu Hội ngộ đến Chung kết là một chặng dài",
    noiDung: "Chương trình bắt đầu từ tháng 6 và còn kéo dài nhiều tháng. Giữ sức và giữ tinh thần suốt cả chặng khó hơn là toả sáng một đêm — giống hệt việc học cả một năm." },
  { tieuDe: "Đinh Mạnh Ninh trở lại sau nhiều năm",
    noiDung: "Đinh Mạnh Ninh từng rất nổi tiếng cách đây hơn mười năm rồi ít xuất hiện. Mùa này anh quay lại sân khấu lớn, chứng minh rằng chưa bao giờ là quá muộn để bắt đầu lại." },
  { tieuDe: "Thái VG và vai trò thủ lĩnh",
    noiDung: "Ở Công diễn 3, Thái VG làm thủ lĩnh Nhà Hợp Lực. Làm thủ lĩnh nghĩa là phải chia việc, động viên đồng đội và chịu trách nhiệm nếu nhóm thua — không chỉ lo phần hát của mình." },
  { tieuDe: "Mew Amazing — người đứng sau nhiều bản hit",
    noiDung: "Mew Amazing là nhạc sĩ đã viết nhiều ca khúc nổi tiếng cho các ca sĩ khác. Mùa này anh bước ra ánh đèn với tư cách người biểu diễn." },
  { tieuDe: "Khán giả cũng góp phần quyết định",
    noiDung: "Kết quả mỗi công diễn có phần từ bình chọn của khán giả tại trường quay. Nghĩa là hát hay thôi chưa đủ, còn phải kể được câu chuyện làm người nghe rung động." },
  { tieuDe: "Osad và Hà An Huy — lứa nghệ sĩ trẻ",
    noiDung: "Osad và Hà An Huy thuộc nhóm trẻ nhất chương trình. Đứng cạnh những đàn anh đi trước cả chục năm, họ học được rất nhiều chỉ qua mỗi buổi tập." },
  { tieuDe: "Sự cố kĩ thuật cũng là chuyện thường",
    noiDung: "Tập 2 mùa này gặp sự cố kĩ thuật khiến lịch phát sóng phải điều chỉnh. Ngay cả một ê-kíp lớn cũng có lúc sai sót; điều quan trọng là nhận ra và khắc phục." },
  { tieuDe: "Will và Jun Phạm — từ 365 đến sân khấu riêng",
    noiDung: "Will và Jun Phạm từng cùng nhóm nhạc 365 nhiều năm trước. Giờ mỗi người một hướng đi, gặp lại nhau trong cùng một chương trình." },
  { tieuDe: "Nhạc dân gian được làm mới",
    noiDung: "Điều được khen nhiều nhất qua các mùa là cách chương trình đưa chất liệu dân gian, dân ca vào tiết mục hiện đại. Nhiều bạn trẻ nhờ đó mới biết tới những làn điệu của ông bà." },
  { tieuDe: "Mỗi công diễn là một chủ đề khác nhau",
    noiDung: "Các anh tài không được hát lại một kiểu suốt chương trình: mỗi vòng có chủ đề riêng, buộc họ phải thử phong cách mới. Giống như Kim mỗi tuần lại học một dạng bài khác vậy." },
];
